<?php 


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.twinspires.com/adw/todays-tracks?affid=2800&sortOrder=nextUp');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 30);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: www.twinspires.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: ^^';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cookie: _abck=1289DC72E6C212A2C51A454BD64DDE8A~-1~YAAQ5l3aFyx3SCGBAQAAlMqRZAiy4Ov0TJf4EZZA31fAqj2vatM39qR18rA76HVskjO4m4uGXNTc/L2Eghd65pPjvy+zPXcuFLbsVE924wNywTAJaS2bFTwEE7b2p2zHjtgeaUcuocCJ4M8/ZTvCA34yNOc9U1YePXnb7gxr2V2S/mX4JiW+dCuXsTWlNHM1gO/F6mzFn9hlPBRZEZY6kz1Y5f2kTS4llv0ZDwogsrrqfpf7/SQEdeJfNeu/tWHxXE7JgoqLNyIW1NIysYDjBEYBgOwljAUJmwWycVNGbtvfTOvGh1/lbPt4L+SFhgbdkd4oGPEmGHSI1dfdjzfx9ULracY5+EA3Yj1LqCEDqn6D7NFrsxmwYQsHILugKZpgpXNE7Rx61p83vu4YrmY=~-1~-1~-1; ak_bmsc=269603023D0ED13C857B4CF594500AFF~000000000000000000000000000000~YAAQ5l3aFy13SCGBAQAAlMqRZBAnaPo/R/W5lN3OG3ushTH/Lp4tfEHrVbfqEBeUjEBXaWvTDAJpI+pevFP7cetd1ocnnjrjKIBypt7Fnq0QnXMAE/l/Mb3Bhw3gQpokVCCheKwC2n0e6Xfm06b8tIb2NQiEXkrAgkvVojoueISWuse9/QFVi3zhTbROy8M8s8j08v6xHsaw0O/c0y61wSxqgDg455XETGYY0NmOlQDGXi3whRZBjy8juEWfmufCEf3U+BIxW8eQfWMpo81IzQE8vXjT4ZAn8wDvDJVHwVN3Zh6Kuc4H9S8qnOpvt6+aViphZmSaF43te9QzGBvYXulWxmLbMAuygvIPi+yU0H4oeKDNnkMEPY0ZArl9Lfv35wkCmRmY4ajFVPCnVysiwg==; bm_sz=F0F0F2E35FCC8A94A542F0BF235A31AA~YAAQ5l3aFy53SCGBAQAAlMqRZBCzBGBNSg70Zdg1TZWpv1nxVhRXZ4vvDblv/d246wpV5nGTyzDx7eVzKBQZdfcfOoFlHdvLsFzrIv3HGEn+T1Of2zN0qH8oPfXZAAArTdgbfWpaVZjx1C/9wDUWeNQbAMZANStwtjOeOZyNO8I6OS5+uveU15EDLNZ1QppIgDVqV0+xpgEvmwIrTGDYYkyydRi9NQLZ6MoUkPvtlKuG4HDQk0nOOLTlIyRamTrDBaNeUjKwhgCRSJ45zFAtjMSn4CABfJi1e1c/Vord+jb8S1c+gVIc~3688002~3486007';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 2);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

var_dump($result);