<?php
 // 
// echo 'opcache_reset3<br>';
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
if (!isset($_SESSION)) {
    session_start();
} require_once('../Connections/conexionbanca.php');

date_default_timezone_set("Pacific/Honolulu");
$fecha=fechaactualbd();
$hora=horaactual();
$fechahora=$fecha.' '.$hora;
echo '.<br>';
//echo $fechahora.'<br>';

$query_Recordset1_alertas = sprintf(
        "/* PARSEADORES1 Venta_Animalitos\curl_ani3.php - QUERY 1 */ SELECT * FROM 
alertas
WHERE  
idalertas=34",
        GetSQLValueString($fecha, "date")
    );
    $Recordset1_alertas = mysqli_query($conexionbanca, $query_Recordset1_alertas) or die(mysqli_error($conexionbanca));
    $row_Recordset1_alertas = mysqli_fetch_assoc($Recordset1_alertas);
    $totalRows_Recordset1_alertas = mysqli_num_rows($Recordset1_alertas);
    echo 'Idalertas= '.$row_Recordset1_alertas['Idalertas'].'<br>';

    $mini_para_repetir='-'.$row_Recordset1_alertas['mini_para_repetir'].' second';
    $tiemponorepeticion = strtotime($mini_para_repetir, strtotime($hora)) ;
    $tiemponorepeticion = date('H:i:s', $tiemponorepeticion);
    $tiemponorepeticion = $fecha.' '.$tiemponorepeticion;
    //echo 'tiemponorepeticion= '.$tiemponorepeticion.'<br>';


    $min_para_reportar='-'.$row_Recordset1_alertas['min_para_reportar'].' minute';
    $tiemporeportar = strtotime($min_para_reportar, strtotime($hora)) ;
    $tiemporeportar = date('H:i:s', $tiemporeportar);
    $tiemporeportar = $fecha.' '.$tiemporeportar;
    //echo '$tiemporeportar= '.$tiemporeportar.'<br>';
if($row_Recordset1_alertas['horainicio']<$hora & $row_Recordset1_alertas['horafin']>$hora){}else{
echo 'no esta en el rango de horas de trabjo si desea que se ejecute modificque la hora de ejecucion permitida<br>';}
if($row_Recordset1_alertas['activo_archivo']==0){}else{
echo 'no esta activo el codigo por lo tanto no se ejecutara modifiquelo en alertas para que se pueda ejecutar<br>';}
if($tiemponorepeticion>$row_Recordset1_alertas['ultima_bien']){}else{
echo 'no a pasado el tiempo para que se pueda ejecutar de nuevo si desea que se ejecute antes redusca o elimine el tiempo de reposo entre ejecucion en alertas para que se pueda ejecutar<br>';}
//hora de inicio y hora de fin y si esta activo
if($row_Recordset1_alertas['horainicio']<$hora & $row_Recordset1_alertas['horafin']>$hora & $row_Recordset1_alertas['activo_archivo']==0 & $tiemponorepeticion>$row_Recordset1_alertas['ultima_bien']){
//echo 'hora de inicio y hora de fin<br>';


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$ani_resul_array[] =array(
    "id_Loteria"    => "id_Loteria",
    "Loteria"    => "Loteria",
    "Hora"    => "Hora",
    "Nombre"  => "Nombre",
    "Numero"  => "Numero",
);
$numeroanibasedatos=99999;
$horaTxt=horaactual(); $FechaTxt=fechaactualbd(); $fechahora=$FechaTxt.' '.$horaTxt;
$datetime =$fechahora; $datetime = strtotime('-6 hour', strtotime($datetime)); $datetime = date('Y-m-j H:i:s', $datetime);

$datetime = strtotime('+6 hour', strtotime($horaTxt));
$datetime = strtotime('+0 minute', $datetime);
$fechahora2 = date('Y-m-d H:i:s', $datetime);
echo $fechahora2.'<br>';

//echo substr($FechaTxt, 0, 5).'<br>';




$query_Recordset1111_solteos = sprintf(
    "/* PARSEADORES1 Venta_Animalitos\curl_ani3.php - QUERY 2 */ SELECT id_solteo_ani4,
    id_Loterias_y_nombres_ani4,
    fechahora_solteo_ani4
  FROM  ani4_solteos
  WHERE 
  id_Loterias_y_nombres_ani4 = 6 AND
  fechahora_solteo_ani4 >= %s AND
  fechahora_solteo_ani4 <= %s 
  ORDER BY id_solteo_ani4 ASC",
  GetSQLValueString($fechahora.' 00:00:01', "date"), GetSQLValueString($fechahora2, "date") );
  $Recordset1111_solteos =mysqli_query($conexionbanca, $query_Recordset1111_solteos) or die(mysqli_error($conexionbanca));
  $row_Recordset1111_solteos = mysqli_fetch_assoc($Recordset1111_solteos);
  $totalRows_Recordset1111_solteo = mysqli_num_rows($Recordset1111_solteos);
  echo $totalRows_Recordset1111_solteo.' $totalRows_Recordset1111_solteo<br>';
do {


$query_Recordset1_solteos_resultados = sprintf(
    "/* PARSEADORES1 Venta_Animalitos\curl_ani3.php - QUERY 3 */ SELECT id_resultado_ani6
    FROM  ani6_resultados
    WHERE 
    id_solteo_ani6 = %s  AND
    fechahora_resultado_ani6 >= %s AND fechahora_resultado_ani6 <= %s
     ORDER BY id_resultado_ani6  DESC LIMIT 1",
    GetSQLValueString($row_Recordset1111_solteos['id_solteo_ani4'], "int"),
    GetSQLValueString($FechaTxt.' 00:00:01', "date"), 
    GetSQLValueString($FechaTxt.' 23:59:59', "date") );
    $Recordset1_solteos_resultados =mysqli_query($conexionbanca, $query_Recordset1_solteos_resultados) or die(mysqli_error($conexionbanca));
    $row_Recordset1_solteos_resultados = mysqli_fetch_assoc($Recordset1_solteos_resultados);
    $totalRows_Recordset1_solteos_resultados = mysqli_num_rows($Recordset1_solteos_resultados);
if($totalRows_Recordset1_solteos_resultados==0){
    echo 'fechahora_solteo_ani4 '.$row_Recordset1111_solteos['fechahora_solteo_ani4'].'<br>';
    echo 'id_Loterias_y_nombres_ani4 '.$row_Recordset1111_solteos['id_Loterias_y_nombres_ani4'].'<br>';
    echo 'id_solteo_ani4 '.$row_Recordset1111_solteos['id_solteo_ani4'].'<br><br><br>';
}
} while ($row_Recordset1111_solteos = mysqli_fetch_assoc($Recordset1111_solteos));



























$url='https://safariactivo.com/';
echo $url.'<br>';

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_SSLVERSION, 'CURL_SSLVERSION_TLSv1_2');
//curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2); 
//curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
//curl_setopt($ch, CURLOPT_SSLVERSION, 6);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();

$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cache-Control: no-cache';
//$headers[] = 'Cookie: _ga_7V4WPRXM60=GS1.1.1695890578.1.0.1695890578.0.0.0; _ga=GA1.1.174023334.1695890579';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Sec-Ch-Ua: ^^Google';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$datoscurl = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
    $updateSQL = sprintf(
        "UPDATE alertas SET contadorfallos=1+contadorfallos
                          WHERE idalertas=%s",
        GetSQLValueString($row_Recordset1_alertas['Idalertas'], "int")
    );
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
    if($row_Recordset1_alertas['contadorfallos']>$row_Recordset1_alertas['cont_fallos_reporte'] && $row_Recordset1_alertas['id_chat_error']<>0 && $tiemporeportar>$row_Recordset1_alertas['ultima_bien']){
        echo 'se envio alerta por contador de fallos<br>';
    $msj=$row_Recordset1_alertas['mensajealerta_error'];
    $msjx=utf8_encode($msj);
    $post=[
    'chat_id'=>$row_Recordset1_alertas['id_chat_error'],
    'text'=>$msjx,
    ];
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "https://api.telegram.org/bot309341364:AAETe6H8z5HXbqdv5XhpTEY-nsfBKtYQ0mE/sendMessage");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    curl_exec($ch);
    curl_close($ch);
    
    //-214345883
    //al reportar en telegran se reinicia el contador de fallos y cuando se ejecuta todo bien tambien
    $updateSQL = sprintf(
        "UPDATE alertas SET contadorfallos=%s
                          WHERE idalertas=%s",
        GetSQLValueString(0, "int"),
        GetSQLValueString($row_Recordset1_alertas['Idalertas'], "int")
    );
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
}}
curl_close($ch);

$datoscurl=preg_replace('/\s+/', 's7s', $datoscurl);
$datoscurl=str_replace('(', 'ZZ', $datoscurl); 
$datoscurl=str_replace(')', 'ZZ', $datoscurl);
$borrardecurl=array(";", "=", "<", ">", "\\", "{", "}", "[", "]" , "#" , "'" , '"' , "/" , '%');
$datoscurl=str_replace($borrardecurl, '', $datoscurl);


$ja=0;

$continuar=0;

if(strlen($datoscurl)>100){
    //echo $datoscurl;
    $updateSQL = sprintf(
        "UPDATE alertas SET contadorfallos=0, ultima_bien=%s
                          WHERE idalertas=%s",
        GetSQLValueString($fechahora, "date"),
        GetSQLValueString($row_Recordset1_alertas['Idalertas'], "int")
    );
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
    //$datoscurl=explode('srcimagesfigurasanimalito', $datoscurl);
    $datoscurl=explode('-s7sResultadoss7ssafaris7spluss7s--', $datoscurl);

    foreach ($datoscurl as $datoscurl2) { 

        
if(strpos($datoscurl2, 'copyrights')) { }else{
// echo $datoscurl2;


  echo '<br><br><br><br><br>';
//   






if($continuar==0){
    //echo $datoscurl2.'<br><br><br><br><br><br><br><br><br><br>';


    //stds7sdivs7sclassproducto
$datoscurl2x=explode('srcimagesfigurasanimalito', $datoscurl2);
    foreach ($datoscurl2x as $datoscurl2xx) { 
        if(strpos($datoscurl2xx, 'UTF-8')) { }else{
    $datoscurl2xx=substr ($datoscurl2xx, 0, 150); 
    //echo $datoscurl2xx;
    
    echo '<br>';

if(strpos($datoscurl2xx, 'pngs7swidth100s7sheight100h3')) { 
    //echo $datoscurl2xx.'<br>';
    //var_dump($datoscurl2xx);

//preg_match_all("((.*)brspans7sclassVsOddsVSspanbr(.*)tds7stds7swidth25(.*)-(.*)tds7stds7sclasstext-center(.*))siU", $datoscurl2, $datoscurl3);
//preg_match_all("((.*)salt(.*)s7s(.*)s7s(.*)s7s(.*)s7sdivs7sdivs7sclassstep-contents7sh4s7(.*))siU", $datoscurl2xx, $datoscurl2xx2);

               //s(.*).pngs7swidth100s7sheight100h(.*)s7s-s7s(.*)h3pSafariActivos7s(.*)psectiondivdivs7sclass4us7s12u$ZZmediumZZsections7sclassboximgs7s
preg_match_all("(s(.*).pngs7swidth100s7sheight100h(.*)s7s-s7s(.*)h3pSafariActivos7s(.*)psectiondivdiv(.*))siU", $datoscurl2xx, $datoscurl2xx2);
//var_dump($datoscurl2xx2);
//if($datoscurl2xx2[2][0]>0){

    //foreach ($datoscurl2x as $datoscurl2xx) { 
    if(strlen($datoscurl2xx2[3][0])>1){


echo '<br>id_Loteria 6 ';      
$datoscurl2xx2[4][0]=str_replace('s7s', ' ', $datoscurl2xx2[4][0]);

$datoscurl2xx2[4][0] = strtotime('-0 hour', strtotime($datoscurl2xx2[4][0]));
$datoscurl2xx2[4][0] = strtotime('+0 minute', $datoscurl2xx2[4][0]);
$datoscurl2xx2[4][0] = date('Y-m-d H:i:s', $datoscurl2xx2[4][0]);

echo 'Hora '.$datoscurl2xx2[4][0];
echo ' Numero '.$datoscurl2xx2[1][0];
echo ' Nombre '.$datoscurl2xx2[3][0];
echo '<br><br>';
    //echo '<br>';



    $ani_resul_array[] =array(
        "id_Loteria"    => 6,
        "Loteria"    => 'safari activo',
        "Hora"    => $datoscurl2xx2[4][0],
        "Nombre"  => $datoscurl2xx2[3][0],
        "Numero"  => $datoscurl2xx2[1][0],
    );
}

}

}
}}
    





            $continuar=0;
    }}


}
echo '<br>';

$query_Recordset1111_solteos = sprintf(
    "SELECT id_solteo_ani4,
    id_Loterias_y_nombres_ani4,
    fechahora_solteo_ani4
  FROM  ani4_solteos
  WHERE 
  id_Loterias_y_nombres_ani4 = 6 AND
  fechahora_solteo_ani4 >= %s AND
  fechahora_solteo_ani4 <= %s 
  ORDER BY id_solteo_ani4 ASC",
GetSQLValueString($FechaTxt.' 00:00:01', "date"), GetSQLValueString($fechahora2, "date") ); 
  $Recordset1111_solteos =mysqli_query($conexionbanca, $query_Recordset1111_solteos) or die(mysqli_error($conexionbanca));
  $row_Recordset1111_solteos = mysqli_fetch_assoc($Recordset1111_solteos);
  $totalRows_Recordset1111_solteo = mysqli_num_rows($Recordset1111_solteos);
  echo $totalRows_Recordset1111_solteo.' $totalRows_Recordset1111_solteo<br>';











do {


$query_Recordset1_solteos_resultados = sprintf(
    "SELECT id_resultado_ani6
    FROM  ani6_resultados
    WHERE 
    id_solteo_ani6 = %s  AND
    fechahora_resultado_ani6 >= %s AND fechahora_resultado_ani6 <= %s
     ORDER BY id_resultado_ani6  DESC LIMIT 1",
    GetSQLValueString($row_Recordset1111_solteos['id_solteo_ani4'], "int"),
    GetSQLValueString($FechaTxt.' 00:00:01', "date"), 
    GetSQLValueString($FechaTxt.' 23:59:59', "date") );
    $Recordset1_solteos_resultados =mysqli_query($conexionbanca, $query_Recordset1_solteos_resultados) or die(mysqli_error($conexionbanca));
    $row_Recordset1_solteos_resultados = mysqli_fetch_assoc($Recordset1_solteos_resultados);
    $totalRows_Recordset1_solteos_resultados = mysqli_num_rows($Recordset1_solteos_resultados);
    //echo $totalRows_Recordset1_solteos_resultados.' $totalRows_Recordset1_solteos_resultados<br>';

if($totalRows_Recordset1_solteos_resultados==0){
echo 'aquiaqui';

    foreach ($ani_resul_array as $ani_resul_array2) { 
        //var_dump($ani_resul_array2).'<br>';
     $fechahorapagina=$ani_resul_array2["Hora"];
      //$fechahorapagina=$FechaTxt.' '.$ani_resul_array2["Hora"].':00';
      
      echo '$fechahorapagina '.$fechahorapagina.'<br>';
     echo 'fechahora_solteo_ani4 '.$row_Recordset1111_solteos['fechahora_solteo_ani4'].'<br>';
if($row_Recordset1111_solteos['id_Loterias_y_nombres_ani4']==$ani_resul_array2['id_Loteria'] && $row_Recordset1111_solteos['fechahora_solteo_ani4']==$fechahorapagina ){ 
    echo 'aqui vamos siiii<br>';
    var_dump($ani_resul_array2["Hora"]);
echo '<br>';
    echo 'fechahora_solteo_ani4 '.$row_Recordset1111_solteos['fechahora_solteo_ani4'].'<br>';
    echo 'id_Loterias_y_nombres_ani4 '.$row_Recordset1111_solteos['id_Loterias_y_nombres_ani4'].'<br>';
    var_dump($ani_resul_array2["Numero"]);  echo ' Numero..<br>';
   
if($ani_resul_array2["Numero"]=="01"){$ani_resul_array2["Numero"]="1"; echo $ani_resul_array2["Numero"].' Numero 1<br>';}
if($ani_resul_array2["Numero"]=="02"){$ani_resul_array2["Numero"]="2"; echo $ani_resul_array2["Numero"].' Numero 5<br>';}
if($ani_resul_array2["Numero"]=="03"){$ani_resul_array2["Numero"]="3"; echo $ani_resul_array2["Numero"].' Numero 3<br>';}
if($ani_resul_array2["Numero"]=="04"){$ani_resul_array2["Numero"]="4"; echo $ani_resul_array2["Numero"].' Numero 4<br>';}
if($ani_resul_array2["Numero"]=="05"){$ani_resul_array2["Numero"]="5"; echo $ani_resul_array2["Numero"].' Numero 5<br>';}
if($ani_resul_array2["Numero"]=="06"){$ani_resul_array2["Numero"]="6"; echo $ani_resul_array2["Numero"].' Numero 6<br>';}
if($ani_resul_array2["Numero"]=="07"){$ani_resul_array2["Numero"]="7"; echo $ani_resul_array2["Numero"].' Numero 7<br>';}
if($ani_resul_array2["Numero"]=="08"){$ani_resul_array2["Numero"]="8"; echo $ani_resul_array2["Numero"].' Numero 8<br>';}
if($ani_resul_array2["Numero"]=="09"){$ani_resul_array2["Numero"]="9"; echo $ani_resul_array2["Numero"].' Numero 7<br>';}

    echo 'Numero de animalito en loteria '.$ani_resul_array2["Numero"].'<br>';






    $query_Recordset1_3331_ = sprintf(
        "SELECT
        ani1_loterias_y_nombres.id_Loterias_y_nombres_ani1,  ani1_loterias_y_nombres.animales_Loterias_y_nombres_ani1
        FROM ani1_loterias_y_nombres
        WHERE

        ani1_loterias_y_nombres.id_Loterias_y_nombres_ani1 = %s", 
        GetSQLValueString($row_Recordset1111_solteos['id_Loterias_y_nombres_ani4'], "int"));
        $Recordset1_3331_ = mysqli_query($conexionbanca, $query_Recordset1_3331_) or die(mysqli_error($conexionbanca));
        $row_Recordset1_3331_ = mysqli_fetch_assoc($Recordset1_3331_);
        $totalRows_Recordset1_3331_ = mysqli_num_rows($Recordset1_3331_);
        $animales_Loterias_y_nombres_ani1 = explode(",", $row_Recordset1_3331_["animales_Loterias_y_nombres_ani1"]);
        foreach ($animales_Loterias_y_nombres_ani1 as $animales_Loterias_y_nombres_ani1x) {
$animales_Loterias_y_nombres_ani1x = explode(".", $animales_Loterias_y_nombres_ani1x);

//if($ani_resul_array2["Numero"]===08){$ani_resul_array2["Numero"]=8; }
//if($ani_resul_array2["Numero"]===09){$ani_resul_array2["Numero"]=9; }


if($animales_Loterias_y_nombres_ani1x[1]===$ani_resul_array2["Numero"]){ 
    //$numeroanibasedatos=99999;

    







    echo 'Numero animalito en base de datos '.$animales_Loterias_y_nombres_ani1x[0].'<br>'; 
    $numeroanibasedatos=$animales_Loterias_y_nombres_ani1x[0];
}
if($numeroanibasedatos==99999){ 
   //var_dump($animales_Loterias_y_nombres_ani1x[1]); echo  '..<br>';
  // var_dump($ani_resul_array2["Numero"]); echo  '...<br>';

    if($animales_Loterias_y_nombres_ani1x[1]===$ani_resul_array2["Numero"]){ 
    $numeroanibasedatos=$animales_Loterias_y_nombres_ani1x[0]; }}

}
echo 'id_solteo_ani4 '.$row_Recordset1111_solteos['id_solteo_ani4'].'<br>';

$url222="http://parseadores2.us.to/Venta_Animalitos/ani_introducir_resultados.php?idsol=".$row_Recordset1111_solteos['id_solteo_ani4']."&idani=".$numeroanibasedatos."&fecha=".$FechaTxt;




echo $url222.'<br><br>';



$datetimeday = strtotime('+6 hour', strtotime($horaTxt));
$datetimeday = strtotime('-1 day', $datetimeday);
$fechahora2day = date('Y-m-d', $datetimeday);
echo $fechahora2day.' ....fechahora2day...<br>';
$fechahora2day=$fechahora2day.' '.$ani_resul_array2["Hora"].':00';
//$fechahorapagina=$FechaTxt.' '.$ani_resul_array2["Hora"].':00';
//aqui
echo $fechahora2day.' ....fechahora2day22222...<br>';
echo $row_Recordset1111_solteos['id_Loterias_y_nombres_ani4'].' id_Loterias_y_nombres_ani4...<br>';
$query_Recordset1_solteos_resultados2 = sprintf(
    "SELECT *
    FROM  ani6_resultados, ani4_solteos
    WHERE 
    ani4_solteos.id_solteo_ani4 = ani6_resultados.id_solteo_ani6  AND
    ani4_solteos.id_Loterias_y_nombres_ani4 = %s  AND
    ani4_solteos.fechahora_solteo_ani4 = %s
    LIMIT 1",
    GetSQLValueString($row_Recordset1111_solteos['id_Loterias_y_nombres_ani4'], "int"),
    GetSQLValueString($fechahora2day, "date") );
    $Recordset1_solteos_resultados2 =mysqli_query($conexionbanca, $query_Recordset1_solteos_resultados2) or die(mysqli_error($conexionbanca));
    $row_Recordset1_solteos_resultados2 = mysqli_fetch_assoc($Recordset1_solteos_resultados2);
    $totalRows_Recordset1_solteos_resultados2 = mysqli_num_rows($Recordset1_solteos_resultados2);
echo $totalRows_Recordset1_solteos_resultados2.' ...******...<br>';
echo $row_Recordset1_solteos_resultados2['resultado_ani6'].' ...resultado_ani6...<br>';



if($row_Recordset1_solteos_resultados2['resultado_ani6']<>$numeroanibasedatos){ 
if($numeroanibasedatos<>99999){  
$ch2 = curl_init();
curl_setopt($ch2, CURLOPT_URL, $url222);
//curl_setopt($ch, CURLOPT_SSLVERSION, 'CURL_SSLVERSION_TLSv1_2');
//curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2); 
//curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
//curl_setopt($ch, CURLOPT_SSLVERSION, 6);
curl_setopt($ch2, CURLOPT_RETURNTRANSFER, true);
//curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


curl_setopt($ch2, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();

$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cache-Control: no-cache';
//$headers[] = 'Cookie: _ga_7V4WPRXM60=GS1.1.1695890578.1.0.1695890578.0.0.0; _ga=GA1.1.174023334.1695890579';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Sec-Ch-Ua: ^^Google';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36';
curl_setopt($ch2, CURLOPT_HTTPHEADER, $headers);

$datoscurl2222 = curl_exec($ch2);
if (curl_errno($ch2)) {
    echo 'Error:' . curl_error($ch2);
}
curl_close($ch2);
}}








$numeroanibasedatos=99999;
$fechahorapagina=0;
}
}

echo '--------------<br><br><br>';
// 



}






} while ($row_Recordset1111_solteos = mysqli_fetch_assoc($Recordset1111_solteos));



echo '--------------<br><br><br>';

var_dump($ani_resul_array);
}