<?php
if (!isset($_SESSION)){session_start();} require_once('../Connections/conexionbanca.php');
set_time_limit(0);


$query_Recordset111 = sprintf("/* PARSEADORES1 includes\capitalotbbet.php - QUERY 1 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 2 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("capital", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);


?>


<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../css/bootstrap.min4.5.2.css">
    <link href="../fonts/font-awesome.min4.7.0.css" rel="stylesheet">
    <title>CAPITAL PRUEBA</title>
</head>

<body>
    <table BORDER>


        <?php
        echo "<tr>";
        echo "<td>HIPODROMO</td>";
        echo "<td>CARRERA</td>";
		echo "<td>MTP</td>";
        echo "<td>ESTADO</td>";
        echo "</tr>";

function consultaCierrecapitalotbbet($cookie,$conexionbanca) {
	$hipodromo[0]=""; $carrera[0]=""; $estado[0]=""; $estado2[0]=""; $estado3[0]=""; $estado4[0]="";
	$ucookiemanual=0;
$url = 'https://www.capitalotbbet.com/adw/todays-tracks?affid=4200&sortOrder=nextUp';
     // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	 $ch = curl_init();

	 curl_setopt($ch, CURLOPT_URL, $url);
	 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	 curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	 
	 curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
	 curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'capitalcookie.txt');  $ucookiemanual=1;}
	 $headers = array();
	 $headers[] = 'Authority: www.capitalotbbet.com';
	 $headers[] = 'Cache-Control: max-age=0';
	 $headers[] = 'Sec-Ch-Ua: ^^Chromium^^\";v=^^\"94^^\",';
	 $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
	 $headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
	 $headers[] = 'Upgrade-Insecure-Requests: 1';
	 $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.36';
	 $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
	 $headers[] = 'Sec-Fetch-Site: none';
	 $headers[] = 'Sec-Fetch-Mode: navigate';
	 $headers[] = 'Sec-Fetch-User: ?1';
	 $headers[] = 'Sec-Fetch-Dest: document';
	 $headers[] = 'Accept-Language: es-ES,es;q=0.9';
	 if($ucookiemanual==0){ $headers[] = $cookie; }
   //  $headers[] = $row_Recordset111['num_carrera'];
	 
	 curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	 
	 $result2 = curl_exec($ch);
	 if (curl_errno($ch)) {
		 echo 'Error:' . curl_error($ch);

		 $updateSQL = sprintf("/* PARSEADORES1 includes\capitalotbbet.php - QUERY 2 */ UPDATE cookies SET errorcookie=errorcookie+1
WHERE cookinombre=%s",
GetSQLValueString("capital", "text"));
$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
$query_Recordset112 = sprintf("/* PARSEADORES1 includes\capitalotbbet.php - QUERY 3 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 2 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("capital", "text"));   
$Recordset112 = mysqli_query($conexionbanca, $query_Recordset112) or die(mysqli_error($conexionbanca));
$row_Recordset112 = mysqli_fetch_assoc($Recordset112);
$totalRows_Recordset112 = mysqli_num_rows($Recordset112);
if($row_Recordset112['errorcookie']>5){
    $updateSQL = sprintf("/* PARSEADORES1 includes\capitalotbbet.php - QUERY 4 */ UPDATE cookies SET errorcookie=errorcookie+1, cookiefull=0
    WHERE 	id_cookie = 2 AND cookinombre=%s",
    GetSQLValueString("capital", "text"));
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
}


	 }
	 curl_close($ch);






// $str_datos = get_url_contents($url); 
$fulldatos = json_decode($result2,true); 
//var_dump($fulldatos); 

if (isset($fulldatos)) {
	$x=0;
	foreach($fulldatos as $CurrentRace) {
		$hipodromo[$x]=strtoupper($CurrentRace["name"]);
		$carrera[$x]=strtoupper($CurrentRace["currentRaceNumber"]);
		foreach($CurrentRace["races"] as $CurrentRace2) {
		//$cn=strtoupper($CurrentRace["races"]["races"]);

		if ($CurrentRace2["raceNumber"]==$CurrentRace["currentRaceNumber"]){
			//echo strtoupper($CurrentRace2["raceNumber"]);
			//echo strtoupper($CurrentRace2["status"]);
			//echo "</br>";
			$estado[$x]=strtoupper($CurrentRace2["status"]);
			$mtp[$x]=strtoupper($CurrentRace2["mtp"]);
	}
	}
		
		$estado2[$x]=strtoupper($CurrentRace["hasBetTypes"]);
		$estado3[$x]=strtoupper($CurrentRace["allowsConditionalWagering"]);
		$estado4[$x]=strtoupper($CurrentRace["allowsBetShareWagering"]);
		echo "<tr>";
		echo "<td>$hipodromo[$x] </td>";
		echo "<td>$carrera[$x] </td>";
		echo "<td> $mtp[$x] </td>";
		echo "<td> $estado[$x] </td>";
		echo "</tr>";



//echo strtoupper($CurrentRace["currentRaceNumber"]);
//echo "</br>";


$x++;
	}
}
return array($hipodromo, $carrera, $estado, $estado2, $estado3, $estado4, $mtp);
}


list($hipodromo, $carrera, $estado, $estado2, $estado3, $estado4, $mtp)=consultaCierrecapitalotbbet($row_Recordset111['cookiefull'],$conexionbanca);

$f=0;
if ($hipodromo[0]!="") {
	foreach($hipodromo as $hip){
//echo $hip.' ------ '.$carrera[$f].' ------ '.$estado[$f];
//echo "</br>";
$f++;
	}
}
//print($hipodromo);
?>