<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
if (!isset($_SESSION)){session_start();} require_once('../Connections/conexionbanca.php');
$horasistema=horaactual();
$fech=fechaactualbd();

$query_Recordset111 = sprintf("/* PARSEADORES1 includes\capitalotbbet_dividendosrespaldo.php - QUERY 1 */ SELECT * 
	FROM 
	cookies 
	WHERE
    id_cookie = 2 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("capital", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);

function capitalResultssolo($car,$fec,$tip,$BrisCode,$cookie,$conexionbanca){
    $ucookiemanual=0;
	if ($tip==0) $tipoHip="Thoroughbred";
	  else if ($tip==1) $tipoHip="Harness";
		else if ($tip==2) $tipoHip="";
       $url = 'https://www.capitalotbbet.com/api/raceresults/results/'.$fec.'/'.$BrisCode.'/'.$tipoHip.'/'.$car;
echo $url;
//llegada estandar
//$url = 'https://www.capitalotbbet.com/api/raceresults/results/2021-07-24/elp/Thoroughbred/1'; 
//$url = 'localhost/includes/capital_dividendos_llegada_estandar.json'; 
//empate primer lugar
//$url = 'https://www.capitalotbbet.com/api/raceresults/results/2021-05-28/ct/Thoroughbred/5'; 
//$url = 'localhost/includes/capital_dividendos_empate_primer_lugar.json'; 
//empate segundo lugar
//$url = 'https://www.capitalotbbet.com/api/raceresults/results/2021-02-01/DED/Thoroughbred/3'; 
//$url = 'localhost/includes/capital_dividendos_empate_segundo_lugar.json'; 
//empate tercel lugar
//$url = 'https://www.capitalotbbet.com/api/raceresults/results/2021-01-12/LRL/Thoroughbred/5'; 
//$url = 'localhost/includes/capital_dividendos_empate_tercel_lugar.json'; 
//caballo A 
//$url = 'https://www.capitalotbbet.com/api/raceresults/results/2021-07-23/sar/Thoroughbred/3'; 
//$url = 'localhost/includes/capital_dividendos_caballo_A.json'; 
//conall
//$url = 'https://www.capitalotbbet.com/api/raceresults/results/2020-09-04/ALB/Thoroughbred/1'; 
//$url = 'localhost/includes/capital_dividendos_conall.json'; 


     // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	 $ch = curl_init();

	 curl_setopt($ch, CURLOPT_URL, $url);
	 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	 curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	 
	 curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
	 curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
     curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'capitalcookie.txt');  $ucookiemanual=1;}
	 $headers = array();
	 $headers[] = 'Authority: www.capitalotbbet.com';
	 $headers[] = 'Cache-Control: max-age=0';
	 $headers[] = 'Sec-Ch-Ua: ^^Chromium^^\";v=^^\"94^^\",';
	 $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
	 $headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
	 $headers[] = 'Upgrade-Insecure-Requests: 1';
	 $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.36';
	 $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
	 $headers[] = 'Sec-Fetch-Site: none';
	 $headers[] = 'Sec-Fetch-Mode: navigate';
	 $headers[] = 'Sec-Fetch-User: ?1';
	 $headers[] = 'Sec-Fetch-Dest: document';
	 $headers[] = 'Accept-Language: es-ES,es;q=0.9';
	 if($ucookiemanual==0){ $headers[] = $cookie; }
   //  $headers[] = $row_Recordset111['num_carrera'];
	 
	 curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	 
	 $result2 = curl_exec($ch);
	 if (curl_errno($ch)) {
		 echo 'Error:' . curl_error($ch);

         $updateSQL = sprintf("UPDATE cookies SET errorcookie=errorcookie+1
         WHERE 	id_cookie = 2 AND cookinombre=%s",
         GetSQLValueString("capital", "text"));
         $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
         $query_Recordset112 = sprintf("SELECT * 
             FROM 
             cookies 
             WHERE
             id_cookie = 2 AND cookinombre = %s
             LIMIT 1",
             GetSQLValueString("capital", "text"));   
         $Recordset112 = mysqli_query($conexionbanca, $query_Recordset112) or die(mysqli_error($conexionbanca));
         $row_Recordset112 = mysqli_fetch_assoc($Recordset112);
         $totalRows_Recordset112 = mysqli_num_rows($Recordset112);
         if($row_Recordset112['errorcookie']>5){
             $updateSQL = sprintf("UPDATE cookies SET errorcookie=errorcookie+1, cookiefull=0
             WHERE 	id_cookie = 2 AND cookinombre=%s",
             GetSQLValueString("capital", "text"));
             $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
         }
	 }
	 curl_close($ch);





//$str_datos = get_url_contents($url); 
//$fp = fopen('capital_dividendos_conall.json', 'x'); 
//fwrite($fp, $str_datos); 
//fclose($fp);
$fulldatos = json_decode($result2,true); 
//echo '<br>';
//var_dump($fulldatos); 
//echo '<br>';
//$last = end($fulldatos["raceDetails"]["winPools"]);
//$last = $last/1;


if($fulldatos["raceDetails"]<>NULL){
$primer=1;
foreach($fulldatos["raceDetails"]["winPools"] as $primerlugar) {
$primerlu[$primer]=$primerlugar["programNumber"];
//echo 'primerlugar'.$primer.'#ejemplar'.$primerlu[$primer].'<br>';
$divga1[$primer]=$primerlugar["winPayout"];
//echo 'divga '.$divga1[$primer].'<br>';
$divpla1[$primer]=$primerlugar["placePayout"];
//echo 'divpla '.$divpla1[$primer].'<br>';
$divshow1[$primer]=$primerlugar["showPayout"];
//echo 'divshow '.$divshow1[$primer].'<br><br>';
    $primer++;
}
 

$segundo=1;
foreach($fulldatos["raceDetails"]["placePools"] as $segundolugar) {
$segundolu[$segundo]=$segundolugar["programNumber"];
//echo 'segundolugar'.$segundo.'#ejemplar'.$segundolu[$segundo].'<br>';
$divpla2[$segundo]=$segundolugar["placePayout"];
//echo 'divpla.. '.$divpla2[$segundo].'<br>';
$divshow2[$segundo]=$segundolugar["showPayout"];
//echo 'divshow '.$divshow2[$segundo].'<br><br>';
    $segundo++;
}


$tercero=1;
foreach($fulldatos["raceDetails"]["showPools"] as $tercerolugar) {

$tercerlu[$tercero]=$tercerolugar["programNumber"];
//echo 'tercerlugar'.$tercero.'#ejemplar'.$tercerlu[$tercero].'<br>';
$divshow3[$tercero]=$tercerolugar["showPayout"];
//echo 'divshow '.$divshow3[$tercero].'<br><br>';
    $tercero++;
}

$SPc=1;
$TRc=1;
$EXc=1;
foreach($fulldatos["raceDetails"]["exoticPools"] as $exoticas) {
if($exoticas["poolCode"]=="EX"){
    
    $exoticas[$EXc]=$exoticas["poolName"];
   // echo $exoticas[$EXc].'<br>';
    $ordenEX[$EXc]=str_replace("-", "", $exoticas["result"]);
      //  echo $ordenEX[$EXc].'<br>';    
     //   echo $exoticas["base"].' '.$exoticas["value"].'<br>';   
        if($exoticas["base"]==1){ $semultiplicaxEX=2; }
        if($exoticas["base"]==2){ $semultiplicaxEX=1; }
        if($exoticas["base"]==0.5){ $semultiplicaxEX=4; }
        if($exoticas["base"]==0.2){ $semultiplicaxEX=10; }
        if($exoticas["base"]==0.1){ $semultiplicaxEX=20; }
        $divEX[$EXc]=$exoticas["value"]*$semultiplicaxEX;
    //    echo $divEX[$EXc].'<br><br>';  

        $EXc++; 
}
if($exoticas["poolCode"]=="TR"){
  //  echo $exoticas["poolName"].$TRc.'<br>';  
    $ordenTR[$TRc]=str_replace("-", "", $exoticas["result"]);
  //  echo $ordenTR[$TRc].'<br>';   
  //  echo $exoticas["base"].' '.$exoticas["value"].'<br>';     
    if($exoticas["base"]==1){ $semultiplicaxTR=2; }
    if($exoticas["base"]==2){ $semultiplicaxTR=1; }
    if($exoticas["base"]==0.5){ $semultiplicaxTR=4; }
    if($exoticas["base"]==0.2){ $semultiplicaxTR=10; }
    if($exoticas["base"]==0.1){ $semultiplicaxTR=20; }
    $divTR[$TRc]=$exoticas["value"]*$semultiplicaxTR;
  //  echo $divTR[$TRc].'<br><br>';  
    $TRc++;
}
if($exoticas["poolCode"]=="QD"){
    $exoticasSP[$SPc]=$exoticas["poolName"];
   // echo $exoticasSP[$SPc].'<br>';
    $ordenSP[$SPc]=str_replace("-", "", $exoticas["result"]);
   // echo $ordenSP[$SPc].'<br>';      
   // echo $exoticas["base"].' '.$exoticas["value"].'<br>';    
    if($exoticas["base"]==1){ $semultiplicaxSP=2; }
    if($exoticas["base"]==2){ $semultiplicaxSP=1; }
    if($exoticas["base"]==0.5){ $semultiplicaxSP=4; }
    if($exoticas["base"]==0.2){ $semultiplicaxSP=10; }
    if($exoticas["base"]==0.1){ $semultiplicaxSP=20; }
    $divSP[$SPc]=$exoticas["value"]*$semultiplicaxSP;
   // echo $divSP[$SPc].'<br><br>';  
    $SPc++;  
}}

//echo '<br>';

if (!isset($divga1[1])){ $primerlu[1]="0"; $divga1[1]=0;  $divpla1[1]=0; $divshow1[1]=0; } //echo $primerlu[1].' divga1 '.$divga1[1].' divpla1 '.$divpla1[1].' divshow1 '.$divshow1[1].'<br>';
if (!isset($divga1[2])){ $primerlu[2]="0"; $divga1[2]=0;  $divpla1[2]=0; $divshow1[2]=0; } //echo $primerlu[2].' divga1 '.$divga1[1].' divpla1 '.$divpla1[2].' divshow1 '.$divshow1[2].'<br>';
if (!isset($divga1[3])){ $primerlu[3]="0"; $divga1[3]=0;  $divpla1[3]=0; $divshow1[3]=0; } //echo $primerlu[3].' divga1 '.$divga1[1].' divpla1 '.$divpla1[3].' divshow1 '.$divshow1[3].'<br>';

//echo '<br>';

if (!isset($divpla2[1])){ $segundolu[1]="99"; $divpla2[1]=2; $divshow2[1]=2; } //echo $segundolu[1].' divpla2 '.$divpla2[1].' divshow2 '.$divshow2[1].'<br>';
if (!isset($divpla2[2])){ $segundolu[2]="0"; $divpla2[2]=0; $divshow2[2]=0; } //echo $segundolu[2].' divpla2 '.$divpla2[2].' divshow2 '.$divshow2[2].'<br>';
if (!isset($divpla2[3])){ $segundolu[3]="0"; $divpla2[3]=0; $divshow2[3]=0; } //echo $segundolu[3].' divpla2 '.$divpla2[3].' divshow2 '.$divshow2[3].'<br>';

//echo '<br>';

if (!isset($divshow3[1])){ $tercerlu[1]="0"; $divshow3[1]=0; } //echo $tercerlu[1].' divshow3 '.$divshow3[1].'<br>';
if (!isset($divshow3[2])){ $tercerlu[2]="0"; $divshow3[2]=0; } //echo $tercerlu[2].' divshow3 '.$divshow3[2].'<br>';
if (!isset($divshow3[3])){ $tercerlu[3]="0"; $divshow3[3]=0; } //echo $tercerlu[3].' divshow3 '.$divshow3[3].'<br>';

//echo '<br>';

if (!isset($divEX[1])){ $ordenEX[1]="0/0"; $divEX[1]=0; } //echo $ordenEX[1].' divEX '.$divEX[1].'<br>';
if (!isset($divEX[2])){ $ordenEX[2]="0/0"; $divEX[2]=0; } //echo $ordenEX[2].' divEX '.$divEX[2].'<br>';
if (!isset($divEX[3])){ $ordenEX[3]="0/0"; $divEX[3]=0; } //echo $ordenEX[3].' divEX '.$divEX[3].'<br>';

//echo '<br>';

if (!isset($divTR[1])){ $ordenTR[1]="0/0/0"; $divTR[1]=0; } //echo $ordenTR[1].' divTR '.$divTR[1].'<br>';
if (!isset($divTR[2])){ $ordenTR[2]="0/0/0"; $divTR[2]=0; } //echo $ordenTR[2].' divTR '.$divTR[2].'<br>';
if (!isset($divTR[3])){ $ordenTR[3]="0/0/0"; $divTR[3]=0; } //echo $ordenTR[3].' divTR '.$divTR[3].'<br>';

//echo '<br>';

if (!isset($divSP[1])){ $ordenSP[1]="0/0/0/0"; $divSP[1]=0; } //echo $ordenSP[1].' divSP '.$divSP[1].'<br>';
if (!isset($divSP[2])){ $ordenSP[2]="0/0/0/0"; $divSP[2]=0; } //echo $ordenSP[2].' divSP '.$divSP[2].'<br>';
if (!isset($divSP[3])){ $ordenSP[3]="0/0/0/0"; $divSP[3]=0; } //echo $ordenSP[3].' divSP '.$divSP[3].'<br>';


//echo '<br>';echo '<br>';echo '<br>';



//$est_confirmacion="";
//$control_dividendo="";

$eje_primero=$primerlu[1];
$div_primero_gan=$divga1[1];
$div_primero_pla=$divpla1[1];
$div_primero_sho=$divshow1[1];

$eje_segundo=$segundolu[1];
$div_segundo_pla=$divpla2[1];
$div_segundo_sho=$divshow2[1];

$eje_tercero=$tercerlu[1];
$div_tercero_sho=$divshow3[1];

$eje_doble_primero=$primerlu[2];
$div_doble_primero_gan=$divga1[2];
$div_doble_primero_pla=$divpla1[2];
$div_doble_primero_sho=$divshow1[2];

$eje_doble_segundo=$segundolu[2];
$div_doble_segundo_pla=$divpla2[2];
$div_doble_segundo_sho=$divshow2[2];

$eje_doble_tercero=$tercerlu[2];
$div_doble_tercero_sho=$divshow3[2];

$eje_triple_primero=$primerlu[3];
$div_triple_primero_gan=$divga1[3];
$div_triple_primero_pla=$divpla1[3];
$div_triple_primero_sho=$divshow1[3];

$eje_triple_segundo=$segundolu[3];
$div_triple_segundo_pla=$divpla2[3];
$div_triple_segundo_sho=$divshow2[3];

$eje_triple_tercero=$tercerlu[3];
$div_triple_tercero_sho=$divshow3[3];

$eje_cuarto="0";
$div_exacta=$divEX[1];
$fac_exacta=2;
$div_trifecta=$divTR[1];
$fac_trifecta=2;
$div_superfecta=$divSP[1];
$fac_superfecta=2;
$div_exacta_doble=$divEX[2];
$div_exacta_triple=$divEX[3];
$div_trifecta_doble=$divTR[2];
$div_trifecta_triple=$divTR[3];
$div_superfecta_doble=$divSP[2];
$div_superfecta_triple=$divSP[3];

$ord_exacta=$ordenEX[1];
$ord_exacta_doble=$ordenEX[2];
$ord_exacta_triple=$ordenEX[3];

$ord_trifecta=$ordenTR[1];
$ord_trifecta_doble=$ordenTR[2];
$ord_trifecta_triple=$ordenTR[3];

$ord_superfecta=$ordenSP[1];
$ord_superfecta_doble=$ordenSP[2];
$ord_superfecta_triple=$ordenSP[3];
//$hconfir="";
//$cod_carrera="";


  
return array($eje_primero,$div_primero_gan,$div_primero_pla,$div_primero_sho,$eje_segundo,$div_segundo_pla,$div_segundo_sho,$eje_tercero,$div_tercero_sho,$eje_doble_primero,$div_doble_primero_gan,$div_doble_primero_pla,$div_doble_primero_sho,$eje_doble_segundo,$div_doble_segundo_pla,$div_doble_segundo_sho,$eje_doble_tercero,$div_doble_tercero_sho,$eje_triple_primero,$div_triple_primero_gan,$div_triple_primero_pla,$div_triple_primero_sho,$eje_triple_segundo,$div_triple_segundo_pla,$div_triple_segundo_sho,$eje_triple_tercero,$div_triple_tercero_sho,$eje_cuarto,$div_exacta,$fac_exacta,$div_trifecta,$fac_trifecta,$div_superfecta,$fac_superfecta,$div_exacta_doble,$div_exacta_triple,$div_trifecta_doble,$div_trifecta_triple,$div_superfecta_doble,$div_superfecta_triple,$ord_exacta,$ord_exacta_doble,$ord_exacta_triple,$ord_trifecta,$ord_trifecta_doble,$ord_trifecta_triple,$ord_superfecta,$ord_superfecta_doble,$ord_superfecta_triple);
}
echo $url;
}	

$query_Recordset1 = sprintf("SELECT * 
	FROM 
	hipodromo,
	carrera 
	WHERE
	hipodromo.nom_hipodromo = carrera.nom_hipodromo AND
	carrera.est_confirmacion = 1 AND
	carrera.est_carrera = 0 AND 
	hipodromo.mtp_twinspire=1 AND
(carrera.confirmandox = 0 OR carrera.confirmandox = 5) AND	
(hipodromo.bus_resultado_tip = 9 OR hipodromo.bus_resultado_tip = 10 OR hipodromo.bus_resultado_tip = 5 OR hipodromo.bus_resultado_tip = 11 OR hipodromo.bus_resultado_tip = 12) AND
	carrera.fec_carrera = %s  ORDER BY RAND() LIMIT 10",
		GetSQLValueString($fech, "date"));  
$Recordset1 = mysqli_query($conexionbanca, $query_Recordset1) or die(mysqli_error($conexionbanca));
$row_Recordset1 = mysqli_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysqli_num_rows($Recordset1);
echo "totalRows_Recordset1 ..".$totalRows_Recordset1;












$resultadoslistos=0;
if ($resultadoslistos==111111){

}

?>


<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- InstanceBegin template="/Templates/BaseAdmin.dwt.php" codeOutsideHTMLIsLocked="false" -->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- InstanceBeginEditable name="doctitle" -->
    <title>.:Dividednos Total 2:.</title>
    <!-- InstanceEndEditable -->
    <!-- InstanceBeginEditable name="head" -->

    <!-- InstanceEndEditable -->
    <!--[if lte IE 7]>
<link type="text/css" rel="stylesheet" media="all" href="../css/screen_ie.css" />
<![endif]-->
    <style>
    body {
        background-color: #eeeeee;
        padding: 0;
        margin: 0 auto;
        font-family: "Lucida Grande", Verdana, Arial, "Bitstream Vera Sans", sans-serif;
        font-size: 11px;
    }
    </style>


    <!-- InstanceBeginEditable name="aHead" -->
    <!-- InstanceEndEditable -->
</head>

<body>






    <div style="background:#20c8a8; color: #FFF; width:100%;">
        <table width="100%" border="0" style="font-family:Verdana, Geneva, sans-serif;font-size:16px; color:#FFFFFF">
            <tr style="color: #906">
                <td height="41" align="right" valign="middle">
                </td>
                <td height="41" align="right" valign="middle">&nbsp;</td>
                <td width="211" height="41" align="right" valign="middle" style="font-size:36px; color:#000000">
                    <?php echo $horasistema ?>
                </td>
                <td width="5" align="right" valign="middle">&nbsp;

                </td>
            </tr>
            <tr align="center">
                <td width="73"> CIERRE</td>
                <td width="688"> HIPÃ“DROMO</td>
                <td colspan="2" align="center">RESULTADOS</td>
            </tr>
        </table>
    </div>
    <?php
if ($totalRows_Recordset1>0) { 
	$t=0;

    do {
        $reguardar=0;
        $procesarjugadas=0;
	if ($totalRows_Recordset1>0)	{
        $car=$row_Recordset1['num_carrera'];
        $fec=$row_Recordset1['fec_carrera'];
        $tip=$row_Recordset1['tip_hipodromo'];
        $BrisCode=$row_Recordset1['pre_twin'];

      list($eje_primero,$div_primero_gan,$div_primero_pla,$div_primero_sho,$eje_segundo,$div_segundo_pla,$div_segundo_sho,$eje_tercero,$div_tercero_sho,$eje_doble_primero,$div_doble_primero_gan,$div_doble_primero_pla,$div_doble_primero_sho,$eje_doble_segundo,$div_doble_segundo_pla,$div_doble_segundo_sho,$eje_doble_tercero,$div_doble_tercero_sho,$eje_triple_primero,$div_triple_primero_gan,$div_triple_primero_pla,$div_triple_primero_sho,$eje_triple_segundo,$div_triple_segundo_pla,$div_triple_segundo_sho,$eje_triple_tercero,$div_triple_tercero_sho,$eje_cuarto,$div_exacta,$fac_exacta,$div_trifecta,$fac_trifecta,$div_superfecta,$fac_superfecta,$div_exacta_doble,$div_exacta_triple,$div_trifecta_doble,$div_trifecta_triple,$div_superfecta_doble,$div_superfecta_triple,$ord_exacta,$ord_exacta_doble,$ord_exacta_triple,$ord_trifecta,$ord_trifecta_doble,$ord_trifecta_triple,$ord_superfecta,$ord_superfecta_doble,$ord_superfecta_triple)=capitalResultssolo($car,$fec,$tip,$BrisCode,$row_Recordset111['cookiefull'],$conexionbanca);



?>
    <table width="100%" border="1" bordercolor="#20c8a8">
        <tr>
            <td width="53" align="center"><?php echo $row_Recordset1['hor_carrera'] ?></td>
            <td style="font-size:16px"><strong>
                    <?php
							if ($row_Recordset1['bus_resultado_tip']==0) $pagina="";
							if ($row_Recordset1['bus_resultado_tip']==1) $pagina="--> TRACK";
							if ($row_Recordset1['bus_resultado_tip']==2) $pagina="--> BASIC TVG";
							if ($row_Recordset1['bus_resultado_tip']==3) $pagina="--> BUILDABET";
							if ($row_Recordset1['bus_resultado_tip']==4) $pagina="--> TWINSPIRES";
							if ($row_Recordset1['bus_resultado_tip']==5) $pagina="--> ";

							list($a,$m,$d)=explode("-",$row_Recordset1['fec_carrera']);
							$fecha=$d."-".$m."-".$a;
							$carrera=$row_Recordset1['nom_hipodromo']." Carr...".$row_Recordset1['num_carrera'];
							echo $carrera." (".$fecha.") "; ?></strong>
            </td>
            <td width="80" align="center">
                <div id="ejes1<?php echo $row_Recordset1['cod_carrera']; ?>">
                    <?php if (isset($eje_primero)) echo $eje_primero; else echo "&nbsp;";?>
                </div>
            </td>
            <td width="40" align="right">
                <div id="divws1<?php echo $row_Recordset1['cod_carrera']; ?>">
                    <?php if (isset($div_primero_gan)) echo $div_primero_gan; else echo "&nbsp;";?>
                </div>
            </td>
            <td width="40" align="right">
                <div id="divps1<?php echo $row_Recordset1['cod_carrera']; ?>">
                    <?php if (isset($div_primero_pla)) echo $div_primero_pla; else echo "&nbsp;";?>
                </div>
            </td>
            <td width="40" align="right">
                <div id="divss1<?php echo $row_Recordset1['cod_carrera']; ?>">
                    <?php if (isset($div_primero_sho)) echo $div_primero_sho; else echo "&nbsp;";?>
                </div>
            </td>

        </tr>
    </table>

    <?php

if ($row_Recordset1['eje_primero']>=1 && $row_Recordset1['eje_primero']==$eje_primero*1 &&
					number_format($row_Recordset1['div_primero_gan'],2)==number_format(floatval($div_primero_gan),2) &&
					number_format($row_Recordset1['div_primero_pla'],2)==number_format(floatval($div_primero_pla),2) &&
					number_format($row_Recordset1['div_primero_sho'],2)==number_format(floatval($div_primero_sho),2) &&
					$row_Recordset1['eje_segundo']==$eje_segundo*1 &&
					number_format($row_Recordset1['div_segundo_pla'],2)==number_format(floatval($div_segundo_pla),2) &&
					number_format($row_Recordset1['div_segundo_sho'],2)==number_format(floatval($div_segundo_sho),2) &&
					$row_Recordset1['eje_tercero']==$eje_tercero*1 &&
					number_format($row_Recordset1['div_tercero_sho'],2)==number_format(floatval($div_tercero_sho),2) &&
					$row_Recordset1['eje_doble_primero']==$eje_doble_primero*1 &&
					number_format($row_Recordset1['div_doble_primero_gan'],2)==number_format(floatval($div_doble_primero_gan),2) &&										
					number_format($row_Recordset1['div_doble_primero_pla'],2)==number_format(floatval($div_doble_primero_pla),2) &&
					number_format($row_Recordset1['div_doble_primero_sho'],2)==number_format(floatval($div_doble_primero_sho),2) &&
					$row_Recordset1['eje_doble_segundo']==$eje_doble_segundo*1 &&
					number_format($row_Recordset1['div_doble_segundo_pla'],2)==number_format(floatval($div_doble_segundo_pla),2) &&
					number_format($row_Recordset1['div_doble_segundo_sho'],2)==number_format(floatval($div_doble_segundo_sho),2) &&
					$row_Recordset1['eje_doble_tercero']==$eje_doble_tercero*1 &&
					number_format($row_Recordset1['div_doble_tercero_sho'],2)==number_format(floatval($div_doble_tercero_sho),2) &&
					$row_Recordset1['eje_triple_primero']==$eje_triple_primero*1 &&
					number_format($row_Recordset1['div_triple_primero_gan'],2)==number_format(floatval($div_triple_primero_gan),2) &&
					number_format($row_Recordset1['div_triple_primero_pla'],2)==number_format(floatval($div_triple_primero_pla),2) &&
					number_format($row_Recordset1['div_triple_primero_sho'],2)==number_format(floatval($div_triple_primero_sho),2) &&
					$row_Recordset1['eje_triple_segundo']==$eje_triple_segundo*1 &&
					number_format($row_Recordset1['div_triple_segundo_pla'],2)==number_format(floatval($div_triple_segundo_pla),2) &&
					number_format($row_Recordset1['div_triple_segundo_sho'],2)==number_format(floatval($div_triple_segundo_sho),2) &&
					$row_Recordset1['eje_triple_tercero']==$eje_triple_tercero*1 &&
					number_format($row_Recordset1['div_triple_tercero_sho'],2)==number_format(floatval($div_triple_tercero_sho),2) &&
					$row_Recordset1['eje_cuarto']==$eje_cuarto*1 &&
					number_format($row_Recordset1['div_exacta'],2)==number_format(floatval($div_exacta),2) &&
					number_format($row_Recordset1['fac_exacta'],2)==number_format(floatval($fac_exacta),2) &&
					number_format($row_Recordset1['div_trifecta'],2)==number_format(floatval($div_trifecta),2) &&
					number_format($row_Recordset1['fac_trifecta'],2)==number_format(floatval($fac_trifecta),2) &&
					number_format($row_Recordset1['div_superfecta'],2)==number_format(floatval($div_superfecta),2) &&
					number_format($row_Recordset1['fac_superfecta'],2)==number_format(floatval($fac_superfecta),2) &&
					number_format($row_Recordset1['div_exacta_doble'],2)==number_format(floatval($div_exacta_doble),2) &&
					number_format($row_Recordset1['div_exacta_triple'],2)==number_format(floatval($div_exacta_triple),2) &&
					number_format($row_Recordset1['div_trifecta_doble'],2)==number_format(floatval($div_trifecta_doble),2) &&
					number_format($row_Recordset1['div_trifecta_triple'],2)==number_format(floatval($div_trifecta_triple),2) &&
					number_format($row_Recordset1['div_superfecta_doble'],2)==number_format(floatval($div_superfecta_doble),2) &&
					number_format($row_Recordset1['div_superfecta_triple'],2)==number_format(floatval($div_superfecta_triple),2) &&
					$row_Recordset1['ord_exacta']==trim($ord_exacta) &&
					$row_Recordset1['ord_exacta_doble']==trim($ord_exacta_doble) &&
					$row_Recordset1['ord_exacta_triple']==trim($ord_exacta_triple) &&
					$row_Recordset1['ord_trifecta']==trim($ord_trifecta) &&
					$row_Recordset1['ord_trifecta_doble']==trim($ord_trifecta_doble) &&
					$row_Recordset1['ord_trifecta_triple']==trim($ord_trifecta_triple) &&
					$row_Recordset1['ord_superfecta']==trim($ord_superfecta) &&
					$row_Recordset1['ord_superfecta_doble']==trim($ord_superfecta_doble) &&
					$row_Recordset1['ord_superfecta_triple']==trim($ord_superfecta_triple)) {
                        $procesarjugadas=1; echo "todo igual<br>";
if($procesarjugadas==1 && $row_Recordset1['control_dividendo']>=1){
    $updateSQL = sprintf("UPDATE carrera 
    SET 
    control_dividendo=%s,
    est_confirmacion=%s
        WHERE cod_carrera=%s",
		GetSQLValueString(2, "int"),
        GetSQLValueString(0, "int"),
        GetSQLValueString($row_Recordset1['cod_carrera'], "int"));
        $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));


  
    $insertSQL = sprintf(
        "INSERT INTO quiencierrayabre 
        (codcarrera, 
        fechaquien, 
        que) 
        VALUES (%s, %s, %s)",
        GetSQLValueString($row_Recordset1['cod_carrera'], "int"),
        GetSQLValueString($fech, "date"),
        GetSQLValueString(28, "int")
    );
    $Result1 = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));
    $cod_carrera=$row_Recordset1['cod_carrera'];

                    $tipoProceso=2;
                    $ch = curl_init();
                    curl_setopt($ch, CURLOPT_URL, 'http://apuestas1.us.to/admin/dividendos_edit2.php?recordID='.$cod_carrera);
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
                    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
                    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 7); 
                    curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
                    $headers = array();
                    $headers[] = 'Cache-Control: max-age=0';
                    $headers[] = 'Sec-Ch-Ua: ^^';
                    $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
                    $headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
                    $headers[] = 'Upgrade-Insecure-Requests: 1';
                    $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
                    $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
                    $headers[] = 'Sec-Fetch-Site: none';
                    $headers[] = 'Sec-Fetch-Mode: navigate';
                    $headers[] = 'Sec-Fetch-User: ?1';
                    $headers[] = 'Sec-Fetch-Dest: document';
                    $headers[] = 'Accept-Language: es-ES,es;q=0.9';
                    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                    $result22 = curl_exec($ch);








                  //include("procesar_resultados_tickets_ame.php");
               echo "<h3><font color='#027BAD'>Proceso de cálculo culminado! ".$carrera."</font></h3>";

}



							}
							else {  $reguardar=1;
                                echo "no es todo igual<br>";
if($eje_primero>=1){

    $insertSQL = sprintf(
        "/* PARSEADORES1 includes\capitalotbbet_dividendosrespaldo.php - QUERY 2 */ INSERT INTO quiencierrayabre 
        (codcarrera, 
        fechaquien, 
        que) 
        VALUES (%s, %s, %s)",
        GetSQLValueString($row_Recordset1['cod_carrera'], "int"),
        GetSQLValueString($fech, "date"),
        GetSQLValueString(23, "int")
    );
    $Result1 = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));


                                $updateSQL = sprintf("/* PARSEADORES1 includes\capitalotbbet_dividendosrespaldo.php - QUERY 3 */ UPDATE carrera 
                                SET 
                                    confirmandox=%s,
                                    est_confirmacion=%s,
                                    control_dividendo=%s,
                                    eje_primero=%s, 
                                    div_primero_gan=%s, 
                                    div_primero_pla=%s, 
                                    div_primero_sho=%s, 
                                    eje_segundo=%s, 
                                    div_segundo_pla=%s, 
                                    div_segundo_sho=%s, 
                                    eje_tercero=%s, 
                                    div_tercero_sho=%s, 
                                    eje_doble_primero=%s, 
                                    div_doble_primero_gan=%s, 
                                    div_doble_primero_pla=%s, 
                                    div_doble_primero_sho=%s, 
                                    eje_doble_segundo=%s, 
                                    div_doble_segundo_pla=%s, 
                                    div_doble_segundo_sho=%s, 
                                    eje_doble_tercero=%s, 
                                    div_doble_tercero_sho=%s, 
                                    eje_triple_primero=%s, 
                                    div_triple_primero_gan=%s, 
                                    div_triple_primero_pla=%s, 
                                    div_triple_primero_sho=%s, 
                                    eje_triple_segundo=%s, 
                                    div_triple_segundo_pla=%s, 
                                    div_triple_segundo_sho=%s, 
                                    eje_triple_tercero=%s, 
                                    div_triple_tercero_sho=%s,
                                    eje_cuarto=%s,
                                    div_exacta=%s,
                                    fac_exacta=%s,
                                    div_trifecta=%s,
                                    fac_trifecta=%s,
                                    div_superfecta=%s,
                                    fac_superfecta=%s,
                                    div_exacta_doble=%s,
                                    div_exacta_triple=%s,
                                    div_trifecta_doble=%s,
                                    div_trifecta_triple=%s,
                                    div_superfecta_doble=%s,
                                    div_superfecta_triple=%s,
                                    
                                    ord_exacta=%s,
                                    ord_exacta_doble=%s,
                                    ord_exacta_triple=%s,
                                    ord_trifecta=%s,
                                    ord_trifecta_doble=%s,
                                    ord_trifecta_triple=%s,
                                    ord_superfecta=%s,
                                    ord_superfecta_doble=%s,
                                    ord_superfecta_triple=%s,
                                    hconfir=%s
                                    
                                WHERE cod_carrera=%s",
                                    GetSQLValueString(5, "int"),
                                    GetSQLValueString(1, "int"),
                                    GetSQLValueString(1, "int"),
                                    GetSQLValueString($eje_primero, "int"),
                                    GetSQLValueString($div_primero_gan, "double"),
                                    GetSQLValueString($div_primero_pla, "double"),
                                    GetSQLValueString($div_primero_sho, "double"),
                                    GetSQLValueString($eje_segundo, "int"),
                                    GetSQLValueString($div_segundo_pla, "double"),
                                    GetSQLValueString($div_segundo_sho, "double"),
                                    GetSQLValueString($eje_tercero, "int"),
                                    GetSQLValueString($div_tercero_sho, "double"),
                                    GetSQLValueString($eje_doble_primero, "int"),
                                    GetSQLValueString($div_doble_primero_gan, "double"),
                                    GetSQLValueString($div_doble_primero_pla, "double"),
                                    GetSQLValueString($div_doble_primero_sho, "double"),
                                    GetSQLValueString($eje_doble_segundo, "int"),
                                    GetSQLValueString($div_doble_segundo_pla, "double"),
                                    GetSQLValueString($div_doble_segundo_sho, "double"),
                                    GetSQLValueString($eje_doble_tercero, "int"),
                                    GetSQLValueString($div_doble_tercero_sho, "double"),
                                    GetSQLValueString($eje_triple_primero, "int"),
                                    GetSQLValueString($div_triple_primero_gan, "double"),
                                    GetSQLValueString($div_triple_primero_pla, "double"),
                                    GetSQLValueString($div_triple_primero_sho, "double"),
                                    GetSQLValueString($eje_triple_segundo, "int"),
                                    GetSQLValueString($div_triple_segundo_pla, "double"),
                                    GetSQLValueString($div_triple_segundo_sho, "double"),
                                    GetSQLValueString($eje_triple_tercero, "int"),
                                    GetSQLValueString($div_triple_tercero_sho, "double"),
                                    GetSQLValueString($eje_cuarto, "int"),
                                    GetSQLValueString($div_exacta, "double"),
                                    GetSQLValueString($fac_exacta, "double"),
                                    GetSQLValueString($div_trifecta, "double"),
                                    GetSQLValueString($fac_trifecta, "double"),
                                    GetSQLValueString($div_superfecta, "double"),
                                    GetSQLValueString($fac_superfecta, "double"),
                                    GetSQLValueString($div_exacta_doble, "double"),
                                    GetSQLValueString($div_exacta_triple, "double"),
                                    GetSQLValueString($div_trifecta_doble, "double"),
                                    GetSQLValueString($div_trifecta_triple, "double"),
                                    GetSQLValueString($div_superfecta_doble, "double"),
                                    GetSQLValueString($div_superfecta_triple, "double"),          
                                    GetSQLValueString($ord_exacta, "text"),
                                    GetSQLValueString($ord_exacta_doble, "text"),
                                    GetSQLValueString($ord_exacta_triple, "text"),
                                    GetSQLValueString($ord_trifecta, "text"),
                                    GetSQLValueString($ord_trifecta_doble, "text"),
                                    GetSQLValueString($ord_trifecta_triple, "text"),
                                    GetSQLValueString($ord_superfecta, "text"),
                                    GetSQLValueString($ord_superfecta_doble, "text"),
                                    GetSQLValueString($ord_superfecta_triple, "text"),
                                    GetSQLValueString($horasistema, "date"),
                                    GetSQLValueString($row_Recordset1['cod_carrera'], "int"));
                                $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));

                            }}
					





}

	} while ($row_Recordset1 = mysqli_fetch_assoc($Recordset1));
	
mysqli_free_result($Recordset1);
}

		?>


</body>