<?php
if (!isset($_SESSION)){session_start();} require_once('../Connections/conexionbanca.php');

$fech=fechaactualbd();
$horasistema=horaactual();
//echo $horasistema;
//echo "<br/>";



?>
<script type="text/javascript">
//<![CDATA[
//<!--
setTimeout("location.reload()", 9999000);
//-->
//]]>
</script>
<div style="background: #096; color: #FFF; width:100%">
    <table width="100%" border="0">
        <tr>
            <td width="464" height="41">HIPODROMO</td>
            <td width="281" align="center">RETIRADOS</td>
        </tr>
    </table>
</div>
<table width="100%" border="1">
    <?php


    $ucookiemanual=0;
	$fecUrl=str_replace("-", "", $fech); $retiro=array(); $programados=0;
	if ($TrackType==0) $hType="Thoroughbred";
		else if ($TrackType==1) $hType="Harness";
			else $hType="";
	//$url = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/OddsMtpPost?affid=2800&debug=off&password=Gltbatm&output=json&track='.$BrisCode.'&username=my_sports&race='.$ncar.'&ip=71.212.122.168&cDate='.$fecUrl.'&type='.$hType;
	//$url = 'https://www.capitalotbbet.com/adw/todays-tracks/'.$BrisCode.'/'.$hType.'/races/'.$ncar.'/entries?affid=4200';
	//con caballo con a
	//$url = 'https://www.capitalotbbet.com/adw/todays-tracks/bel/Thoroughbred/races/1/entries?affid=4200';
	$url = 'http://www.localhost/includes/1x.json';
	//con retirado
	//$url = 'https://www.capitalotbbet.com/adw/todays-tracks/gvl/Thoroughbred/races/2/entries?affid=4200';

     // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	 $ch = curl_init();

	 curl_setopt($ch, CURLOPT_URL, $url);
	 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	 curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	 
	 curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
	 curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
     curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
     curl_setopt($ch, CURLOPT_COOKIEFILE, 'capitalcookie.txt');
	 $headers = array();
	 $headers[] = 'Authority: www.capitalotbbet.com';
	 $headers[] = 'Cache-Control: max-age=0';
	 $headers[] = 'Sec-Ch-Ua: ^^Chromium^^\";v=^^\"94^^\",';
	 $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
	 $headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
	 $headers[] = 'Upgrade-Insecure-Requests: 1';
	 $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.36';
	 $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
	 $headers[] = 'Sec-Fetch-Site: none';
	 $headers[] = 'Sec-Fetch-Mode: navigate';
	 $headers[] = 'Sec-Fetch-User: ?1';
	 $headers[] = 'Sec-Fetch-Dest: document';
	 $headers[] = 'Accept-Language: es-ES,es;q=0.9';
	// if($ucookiemanual==0){ $headers[] = $cookie; }
   //  $headers[] = $row_Recordset111['num_carrera'];
	 
	 curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	 
	 $result2 = curl_exec($ch);
	 if (curl_errno($ch)) {
		 echo 'Error:' . curl_error($ch);



	 }
	 curl_close($ch);
	$fulldatos = json_decode($result2,true); 
	$fulldatos2 = json_decode($result2,true);

		
	
$j=0;
$item_details = array();
foreach($fulldatos as $Entries) {
$espacioono=0;
echo $j.' ';
$programados=$fulldatos[$j]["programNumber"];
echo ' -- '.$fulldatos[$j]["programNumber"].' -- ';
if($fulldatos[$j]["scratched"]<>"true"){ 
	//if (!strpbrk($fulldatos[$j]["programNumber"], 'AB')) {
		$x=0;
		$item_details[]=preg_replace('/[a-zA-Z]/', "",$fulldatos[$j]["programNumber"]);
		$retiro[$x]=$fulldatos[$j]["programNumber"];
		echo " ".$retiro[$x]; echo " retno "; 
		$x++;
	//}
	$espacioono=1;
	echo ' <br>';
}
if($espacioono==0){ echo ' <br>';}
$j++;
}

var_dump($item_details);

echo ' <br><br><br><br><br>';


$j2=0;
foreach($fulldatos2 as $Entries2) {
$espacioono2=0;
echo $j2.' ';
$programados2=$fulldatos2[$j2]["programNumber"];
echo ' -- '.$fulldatos2[$j2]["programNumber"].' -- ';
if($fulldatos2[$j2]["scratched"]=="true"){ 
	$ii=0;
	

		$igual=0;
		$fulldatos2[$j2]["programNumber"]=preg_replace('/[a-zA-Z]/', "",$fulldatos2[$j2]["programNumber"]);
		//if($item_details2[$ii]==$fulldatos2[$j2]["programNumber"]){ echo 'igual'; $igual=1;}	
		
		
		
		if (in_array($fulldatos2[$j2]["programNumber"], $item_details)) {

		}else{  			$x2=0;

			$retiro2[$x2]=$fulldatos2[$j2]["programNumber"];
			echo " ".$retiro2[$x2]; echo " retsi "; 
			$x2++;  }






	

	$ii++;
//	if (!strpbrk($fulldatos2[$j]["programNumber"], 'AB')) {

//	}
$espacioono2=1;
echo ' <br>'; 
}
if($espacioono2==0){ echo ' <br>';}
$j2++;
}




?>
</table>