<?php
 
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

if (!isset($_SESSION)){session_start();} require_once('../Connections/conexionbanca.php');

$fech=fechaactualbd();
$horasistema=horaactual();
//echo $horasistema;
//echo "<br/>";
$query_Recordset1 = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 1 */ SELECT 
		hi.bus_retirado,
		hi.tip_hipodromo,
		hi.pre_twin,
		hi.nom_hipodromo,
		ca.can_caballos,
		ca.cod_carrera,
		ca.num_carrera		 
	FROM 
		carrera ca, 
		hipodromo hi 
	WHERE
		ca.nom_hipodromo=hi.nom_hipodromo AND
	    ca.est_cierre!=3 AND
	    ca.est_confirmacion=1 AND
		hi.mtp_twinspire=1 AND
	(hi.bus_retirado=12 OR hi.bus_retirado=5 OR hi.bus_retirado=8 OR hi.bus_retirado=9) AND
		ca.fec_carrera=%s 
	  ORDER BY RAND() LIMIT 25",
	GetSQLValueString($fech, "date"));  
$Recordset1 = mysqli_query($conexionbanca, $query_Recordset1) or die(mysqli_error($conexionbanca));
$row_Recordset1 = mysqli_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysqli_num_rows($Recordset1);
echo $totalRows_Recordset1;
$query_Recordset111 = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 2 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 2 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("capital", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);
?>
<script type="text/javascript">
//<![CDATA[
//<!--
setTimeout("location.reload()", 9999000);
//-->
//]]>
</script>
<div style="background: #096; color: #FFF; width:100%">
    <table width="100%" border="0">
        <tr>
            <td width="464" height="41">HIPODROMO</td>
            <td width="281" align="center">RETIRADOS</td>
        </tr>
    </table>
</div>
<table width="100%" border="5">
    <?php
if ($totalRows_Recordset1>0) {
function CapitalRetirados($ncar, $TrackType, $BrisCode,$cookie,$conexionbanca) {
    $ucookiemanual=0;
	//$fecUrl=str_replace("-", "", $fech); 
	$retiro=array(); $retiro2=array(); $programados=0;
	if ($TrackType==0) $hType="Thoroughbred";
		else if ($TrackType==1) $hType="Harness";
			else $hType="";
	//$url = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/OddsMtpPost?affid=2800&debug=off&password=Gltbatm&output=json&track='.$BrisCode.'&username=my_sports&race='.$ncar.'&ip=71.212.122.168&cDate='.$fecUrl.'&type='.$hType;
	$url = 'https://www.capitalotbbet.com/adw/todays-tracks/'.$BrisCode.'/'.$hType.'/races/'.$ncar.'/entries?affid=4200';
	echo '<br><br><br>';
	echo $url.'<br>';
	
	//con caballo con a
	//$url = 'https://www.capitalotbbet.com/adw/todays-tracks/fl/Thoroughbred/races/2/entries?affid=4200';
	//con retirado
	//$url = 'https://www.capitalotbbet.com/adw/todays-tracks/gvl/Thoroughbred/races/2/entries?affid=4200';

     // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	 $ch = curl_init();

	 curl_setopt($ch, CURLOPT_URL, $url);
	 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	 curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	 
	 curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
	 curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
	 curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
$headers = array();
$headers[] = 'Authority: www.capitalotbbet.com';
$headers[] = 'Accept: application/json, text/plain, */*';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Cookie: bm_sz=5604469320FBCD6299268AF60B651E96~YAAQ25x6XLnx8+eKAQAAcxJo8hVrPb+DcQsYLfURDylq4SAEDPYtXVTEiK5Ax7cOjaDNPAxg6rdszAyzTIUi6uf7p/5YAekflplZ1GIXiyVpW+t0Mh6GoxxLiinC21VjTUKuu2/+LAZIhe6yy1SRABKeiAa4EQlFJ5WTtiDTH5mllIMVk06pjMTmNoGvIZGckCHLdoQMHp1/dpVhh6rQBvjS5kGLWFbWL6W98e0GiirpqAtAaiCsVl6PMQlDKLtz/l5wdGnrqQFIx/EZU7e0Sh7FsC+Rq3D4RfIIaZKG68L2u98sXqlzs9+G~3683394~3683122; PIM-SESSION-ID=JOiwP6MIWiDRGbMD; _abck=127F23AC101DEFD70171E23C4AD92A48~0~YAAQ25x6XHb48+eKAQAAdmpo8gq8Q0hfcUebr/MXLAMuu2P5I865ojj+Bcu+5DgNjiJcWAwx3wJLuPsuTCQQskEpRZEVtnHLY7X1OqPlfXnR7bM0/yJvLphqb207x4FO00usdUBhST5LB1mCzVsvJrVxnJ5JrKtP71/CBUV14Rf/yNTMIvjXG90YDk69MH2iTFuiG3Sd6ckXIHn4CZfEKaW15PpwedM2MUANfcHDkbFTMlS/MlDH+sSfvFIh91TivGnScJF96c1zu7Dv2Y5w+BoJtQaKIhCdbAUYYX5cAk1eldG1oubMv13ujn7U9KfTux42fz0R3lzJaz1axbj1mvR4YTCKMRPP4i/kfehW+0TCffpGvI8CT9CYMPsL2pOutk2cTdw+9sHmlLQk+/s9BsVf89AnayWda+oiJkoOfg==~-1~-1~-1; SessionID=d36224c6-9040-4036-8073-0c2cf1ad7c5b; ak_bmsc=FF13B60F3D463A0456F4E73891E6015F~000000000000000000000000000000~YAAQ25x6XBIB9OeKAQAAitZo8hVuXkdWhgt3PKsU7TfPASaQGTmKQqKuP0sdS5W4kzRBAACHinGSl6dn/xAqOwAO2vDyz3mNv/za4/Sb0Kak3jc1VdCk7Ps2ZtxWbSXhtkTmwdGXBdrB7niKMu3Nig4vei4w7grydIFBDieBu0sthIxo9P/olOOUW/hPjd9oFDyCiKFyat/BgE63g8aYvYBvkoV2I/skCqC3z75zYNluSnMXiCWM+o2XN0UoEDXeGjGkwyxNKKjWtGORhxW41iIliR40hE2xNhIp6aGIQ5J4WAFX+MOunZ0b15vxVTLZSKm8jR0m2WMzoT2OTs76xjjYtfZDwIN9BLGiHrKE92oBuzDW3F1/yla8LZAjFaouDxYL2/LcNoWuUlztpTQ0gHnzfQBmH0hs2xXX8db695k1PcXdm/oqejj2daFQgHVvaU8ybi5vJ1Lp6CykfXbe3ljFAat9CC+gn/qfbDicjRre7T1oAVPGrYUg+8tTqUZvNbS3PoIVRl1RWWKOQU/AV5cTCE80jfAcLZE9h47IsQWirNx6iLXpMlC/I9GSSyjGkBA=; RT=^^z=1&dm=www.capitalotbbet.com&si=1a8cb9b3-7e2a-4531-9f3c-ac10379b6e59&ss=ln9fpyci&sl=2&tt=9fe&rl=1&bcn=^%^2F^%^2F17de4c1d.akstat.io^%^2F&ld=77hh^^\";';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Referer: https://www.capitalotbbet.com';
$headers[] = 'Sec-Ch-Ua: ^^Google';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sessionid: d36224c6-9040-4036-8073-0c2cf1ad7c5b';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);	 
	 
	 $result2 = curl_exec($ch);
	 if (curl_errno($ch)) {
		 echo 'Error:' . curl_error($ch);

		 $updateSQL = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 3 */ UPDATE cookies SET errorcookie=errorcookie+1
WHERE 	id_cookie = 2 AND cookinombre=%s",
GetSQLValueString("capital", "text"));
$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
$query_Recordset112 = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 4 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 2 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("capital", "text"));   
$Recordset112 = mysqli_query($conexionbanca, $query_Recordset112) or die(mysqli_error($conexionbanca));
$row_Recordset112 = mysqli_fetch_assoc($Recordset112);
$totalRows_Recordset112 = mysqli_num_rows($Recordset112);
if($row_Recordset112['errorcookie']>5){
    $updateSQL = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 5 */ UPDATE cookies SET errorcookie=errorcookie+1, cookiefull=0
    WHERE 	id_cookie = 2 AND cookinombre=%s",
    GetSQLValueString("capital", "text"));
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
}


	 }
	 curl_close($ch);
	 $fulldatos = json_decode($result2,true); 
	 $fulldatos2 = json_decode($result2,true);
	


	 if (isset($fulldatos[0]["programNumber"])) {
	
		$j=0;
		$item_details = array();
		$x=0;
		foreach($fulldatos as $Entries) {
		$espacioono=0;
		//echo $j.' ';
		$programados=$fulldatos[$j]["programNumber"];
		//echo ' -- '.$fulldatos[$j]["programNumber"].' -- ';
		if($fulldatos[$j]["scratched"]<>"true"){ 
			//if (!strpbrk($fulldatos[$j]["programNumber"], 'AB')) {
				
				$item_details[]=preg_replace('/[a-zA-Z]/', "",$fulldatos[$j]["programNumber"]);
				$retiro[$x]=$fulldatos[$j]["programNumber"];
				//echo " ".$retiro[$x]; echo " retno "; 
				$x++;
			//}
			$espacioono=1;
			//echo ' <br>';
		}
		if($espacioono==0){ }
		$j++;
		}
		
		//var_dump($item_details);
		
		//echo ' <br><br><br><br><br>';
		
		
		$j2=0;
		$x2=0;
		foreach($fulldatos2 as $Entries2) {
		$espacioono2=0;



		$programados2=$fulldatos2[$j2]["programNumber"];


		
	
		if($fulldatos2[$j2]["scratched"]=="true"){ 
			$ii=0;
			
		
				$igual=0;
				$fulldatos2[$j2]["programNumber"]=preg_replace('/[a-zA-Z]/', "",$fulldatos2[$j2]["programNumber"]);	
				
				if (in_array($fulldatos2[$j2]["programNumber"], $item_details)) {}else{  			
					$retiro2[$x2]=$fulldatos2[$j2]["programNumber"];
					$x2++;  
					echo 'retiro un caballo<br>';
					var_dump($retiro2);
				echo '<br>';
				}
			$ii++;
		}
		$j2++;
		}
		$programados=max(array($programados2));
		
		return array($retiro2, $programados);
		}









		
}

	do {
		

			
			
			if ($row_Recordset1['pre_twin']!="") {
				
				$ncar=$row_Recordset1['num_carrera'];
				$TrackType=$row_Recordset1['tip_hipodromo'];
				$BrisCode=$row_Recordset1['pre_twin'];
				list($retiro2, $programados)=CapitalRetirados($ncar, $TrackType, $BrisCode,$row_Recordset111['cookiefull'],$conexionbanca);
				echo  $programados."corren<br>";
				var_dump($retiro2);				if ($programados!=$row_Recordset1['can_caballos'] && $programados>3) {
					$cod_carrera=$row_Recordset1['cod_carrera'];

					$updateSQL2 = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 6 */ UPDATE carrera SET can_caballos=%s 
										  WHERE cod_carrera=%s",
								GetSQLValueString($programados, "int"),
								GetSQLValueString($cod_carrera, "int"));
					$Result2 = mysqli_query($conexionbanca, $updateSQL2) or die(mysqli_error($conexionbanca));
					
				}

				
				
				if (isset($retiro2[0])) {
					$ejemRetir="-";
					
					foreach($retiro2 as $ejem){
						$cod_carrera=$row_Recordset1['cod_carrera'];
						$estado=RetiradosSimple($cod_carrera,$ejem);
						$ejemRetir=$ejemRetir.$ejem."-";
						
						if ($estado==0) { // retirar caballo
						
						$query_Recordset11 = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 7 */ SELECT 
		num_rcaballo
		 
	FROM 
retirados
	WHERE
		retirados.num_rcaballo=%s AND
retirados.cod_carrera=%s

	 LIMIT 1",
	GetSQLValueString($ejem, "int"),

GetSQLValueString($cod_carrera, "int"));  
$Recordset11 = mysqli_query($conexionbanca, $query_Recordset11) or die(mysqli_error($conexionbanca));
$row_Recordset11 = mysqli_fetch_assoc($Recordset11);
$totalRows_Recordset11 = mysqli_num_rows($Recordset11);
						
					
						
						
										if ($totalRows_Recordset11==0) {
						echo '<br/>';
						echo 'xxx';
						echo '<br/>';
						
						
						
						
						
												$insertSQL = sprintf("/* PARSEADORES1 includes\capital_retirados.php - QUERY 8 */ INSERT INTO retirados 
										 (quienretiro, cod_carrera, num_rcaballo) VALUES (%s, %s, %s)",
										 GetSQLValueString('capit', "text"),
										 GetSQLValueString($cod_carrera, "int"),
										 GetSQLValueString($ejem, "int"));
							$Result = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));
							
							$insertSQL = sprintf(
								"/* PARSEADORES1 includes\capital_retirados.php - QUERY 9 */ INSERT INTO quiencierrayabre 
								(codcarrera, 
								fechaquien, 
								que) 
								VALUES (%s, %s, %s)",
								GetSQLValueString($cod_carrera, "int"),
								GetSQLValueString($fech, "date"),
								GetSQLValueString(33, "int")
							);
							$Result1 = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));
	
							$tipoProceso=4;
							$num_caballo=$ejem;
							include("../includes/procesar_resultados_tickets_ame.php");
					   



							}
							
							

						}
					}
					?>
    <tr>
        <td width="464">
            <?php 
								echo $row_Recordset1['nom_hipodromo']." ".trim($row_Recordset1['num_carrera'])." ";
							?>
        </td>
        <td width="281" align="center"><?php echo $ejemRetir; ?></td>
    </tr>
    <?php
				}
			}

	} while ($row_Recordset1 = mysqli_fetch_assoc($Recordset1));
}
mysqli_free_result($Recordset1);
?>
</table>