<?php
if (!isset($_SESSION)) {
    session_start();
} require_once('../Connections/conexionbanca.php');
$MM_authorizedUsers = "A"; $MM_restrictGoTo = "../index.php"; include("../includes/comprobar_acceso.php");
set_time_limit(0);
$hoy=fechaactualbd();
//return array($nHi, $dTN, $cCa, $hIn, $tip, $cod_hipodromo, $Horses);

function busHipodromo_twin($identificador)
{
    $hipodromo[0]=0;
    $hipodromo[1]=-1;
    $hipodromo[2]=-1;
    $hipodromo[3]=-1;
    global $conexionbanca;
    $query_ConsultaFuncion = sprintf("/* PARSEADORES1 includes\programar_carreras_auto_twin.php - QUERY 1 */ SELECT cod_hipodromo, pro_desde, nom_hipodromo FROM hipodromo WHERE pre_twin = %s LIMIT 1", GetSQLValueString($identificador, "text"));
    $ConsultaFuncion = mysqli_query($conexionbanca, $query_ConsultaFuncion) or die(mysqli_error($conexionbanca));
    $row_ConsultaFuncion = mysqli_fetch_assoc($ConsultaFuncion);
    $totalRows_ConsultaFuncion = mysqli_num_rows($ConsultaFuncion);
    if ($totalRows_ConsultaFuncion>0) {
        $hipodromo[0]=1;
        $hipodromo[1]=$row_ConsultaFuncion['cod_hipodromo'];
        $hipodromo[2]=$row_ConsultaFuncion['pro_desde'];
        $hipodromo[3]=$row_ConsultaFuncion['nom_hipodromo'];
    }
    mysqli_free_result($ConsultaFuncion);
    return $hipodromo;
}

$query_Recordset111 = sprintf("/* PARSEADORES1 includes\programar_carreras_auto_twin.php - QUERY 2 */ SELECT * 
	FROM 
	cookies 
	WHERE
  id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);




function twinspiresPgm($cookie,$conexionbanca){
$hoy=fechaactualbd();
$fecUrl=str_replace("-", "", $hoy);
$urlH = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/CurrentRace?ip=71.212.122.168&affid=2800&debug=off&username=my_sports&password=Gltbatm&output=json';

$ucookiemanual=0;
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.twinspires.com/adw/todays-tracks?affid=2800&sortOrder=nextUp');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'twinspirecookie.txt');  $ucookiemanual=1;}

$headers = array();
$headers[] = 'Authority: www.twinspires.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: ^^';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
//$headers[] = 'Cookie: _abck=1289DC72E6C212A2C51A454BD64DDE8A~-1~YAAQnAHorG0WRiSBAQAA6vnMaAjyk8sybXmem0gMglng86nrvBdQrdnoagx6GhXj4xDhLbmy/5Kdgh5q/JbKATk8K6zLjhL7+ttA9TirBunvPmHCe3Oqs/iElskUJ3uBySmHxyEHgEQpX0YdduaFiYm8hmV7SSyMOQN9oHVwl2VRH5VjJKgbpR2ioQUncL6kspNlIzJcPyQOkT1LoaClknIIU2H/ifcJl2v64O23Qw/3dwnwxyrOOq3euA1KO8sMMnoLbhq1oKOM65OQK8oesLP0OTTe1I81T/w3NYT7TW+BiFFwqdCvKQXYEKrKb/9Vzp3jwzRH0Y4fYc4PluIJsPn7687Q/XSEniqQAqbw1WCGpYzIkQxN/WdF2fYDf4AGCCmu/rUEgH4TABcbBt0=~-1~-1~-1; ak_bmsc=BE34077C485C60FA083156B660C33446~000000000000000000000000000000~YAAQnAHorG4WRiSBAQAA6vnMaBBiR9Rlx1KlU/blctiI7Kh862F5JZqxRa3ut6wlIhjWYbglM16+cQy9wXTked1t9PWL6R9HoZ8W6yqpbkjYjoQjSnKSJIgBitTHRVMhZFlXrxQiekO2zjRSAbg8V+3ITJQHLWkxsqatK/khebyCrpI4adVsR8hdSLMZLsw8cA8HrYkepb8uh0PpsCZL5PgKLf0QNd1cPQCIy+ScbtLO9J7Zi8A6Tb4UNHVv+FZg9x35cMgz2O4GfLdHnbHMtR0IQha9ipR3RYwdUFFrR64JKUj9FUwJPLL23r9Dz4UNW20DILqog3hYHdF7jRd3t0SN20sbG/4RGLoiF7D0Yy2b9YXEcLj4Ga2jjATPby4+sDEyj/cWN+0zmFPbUlb44A==; bm_sz=AD1E5CF28066F552CAD338F16345D50D~YAAQnAHorG8WRiSBAQAA6vnMaBCtZs+mak0NrqIKIYRWnPpw1uMm66tFculBrnYkFuj6u9f+OC7Rs7tBWs6o17teBEV3/XyIVckspYvC1y68v3A88sZQq1iWxIDj4Xo/Yhd64epUWLFd80w9CYxd5BoQo0TftFWZ/e6dK8T4RthLPiLAc3oaruxXg/L0J/td07tnPLEgb2dDEeX4aP9RZdPj9ogdVVXa7eyMUaMc9o8ekRtLVlzNHFmp5pbELZ/47QNe8qSGJbsxesE1Jfu9Y/nCqVwY7WLnPbdTnAQ++1tJWGpWJrQl~3356211~3294533';
if($ucookiemanual==0){ $headers[] = $cookie; }

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 2);

$result = curl_exec($ch);
if (curl_errno($ch)) {
  echo 'Error:' . curl_error($ch);
}
curl_close($ch);











//$str_datos = get_url_contents($urlH); 
//$fulldatos = json_decode($str_datos,true); 
$fulldatos = json_decode($result,true); 

//var_dump($fulldatos[0]);

$nHi[0]=""; $dTN[0]=""; $cCa[0]=""; $abb[0]=""; $hIn[0]=""; $tip[0]=""; $cHi[0]="";
$cod_hipodromo[0]=""; $y=0; $i=0; $z=0;  $Horses[0]="";
$hipHoy=array();$TrackType=array();
if (isset($fulldatos)) {

  foreach($fulldatos as $CurrentRace) {
    $x=0;  $x1=0;
    $currentRaceNumber=$CurrentRace["currentRaceNumber"];
    $fecCar=$CurrentRace["races"][1]["raceDate"];
    //echo  $fecCar.'<br>';
    if ($fecCar==$hoy) {
    //  echo '<br>aqui estoy <br>';
      $hipHoy[$i]=strtoupper($CurrentRace["brisCode"]);
      $dTN[$z]=strtoupper($CurrentRace["brisCode"]);
      //echo  $hipHoy[$i].'<br>';
      $TrackType[$i]=$CurrentRace["type"];
      //echo  $TrackType[$i].'<br>';
      $nHi[$z]=$CurrentRace["name"];
    //  echo $nHi[$z].' nombre hipodromo<br>';
      $hIn[$z]="01:00:00";
      $tip[$z]=$CurrentRace["type"];
     // echo $tip[$z].' tipo<br>';
      $n=strtoupper($CurrentRace["brisCode"]); 
      $hi=busHipodromo_twin($n);
      $cod_hipodromo[$z]=$hi[1]; 
    //  echo $cod_hipodromo[$z].'<br>';
      //$Horses[$z]="20";
    //  echo $Horses[$z].' caballos<br>';
      if(strpos($nHi[$z], 'Simulcast')){ $simulcastx[$z]=1;}else{ $simulcastx[$z]=0;}
    //  echo $simulcast[$z].' silmulcar<br>';
      //$cCa[$z]=$CurrentRace["races"][2]["raceNumber"];
      $cantEjem=20;
      foreach($CurrentRace["races"] as $CurrentRacex2) {
        if($simulcastx[$z]==1){ 
          //$silmu=1;
          //$simulcast[$z].=",".$silmu;
          //$Horsesx[$z]="20";
          //$Horses[$z].=",".$Horsesx[$z];

          $cantEjem=20;
          if ($x1==0){
          
                      //$silmu=1;
        $simul=1;
        $simulcast[$z]=1;
          }else {
            $simulcast[$z].=",".$simul;
          
          }
          $x1++;


          }else{ 


            if ($x1==0){
                      //$silmu=1;
                      $simul=0;
                      $simulcast[$z]=0;
                    }else {
                      $simulcast[$z].=",".$simul;
                    
                    }
                    $x1++;
          
          }
          




              $cantEjem=20;
              if ($x==0) $Horses[$z]=$cantEjem;
              else $Horses[$z].=",".$cantEjem;
              $x++;

//var_dump($CurrentRacex2);
$cantcca=$CurrentRacex2["raceNumber"];
      }
      $cCa[$z]=$cantcca;

    //  echo $cCa[$z].' cantidad carreras<br>';
      //races
//raceNumber


      $z++;
      $i++;
    }
  }

}
return array($nHi, $dTN, $cCa, $hIn, $tip, $cod_hipodromo, $Horses, $simulcast);
//return array($nHi, $dTN, $cCa, $hIn, $tip, $cod_hipodromo, $Horses);

// listo$nHi, listo$dTN, $cCa, listgo$tip, listo$cod_hipodromo, listo$Horses, listo$simulcast
}








list($hipodomo, $pre, $cantidad, $horainicio, $tipocarrera, $cod_hipodromo, $Horses, $simulcast)=twinspiresPgm($row_Recordset111['cookiefull'],$conexionbanca);
// nombre de	prefijo		cantidad	hora de		tipo
// hipodromo 	hipodromo 	carreras	inicio		carrera
?>
<table width="100%" border="0" cellpadding="0" cellspacing="0" 
	style="font-family:'Lucida Grande','Lucida Sans Unicode','Lucida Sans','DejaVu Sans',Verdana,sans-serif;">
	<tr>
	  <td height="32" colspan="6">&nbsp;</td>
  </tr>
	<tr style="background: #028A96; color:#FFFFFF; height:30px; text-align:center">
        <td width="32%">HIPODROMO</td>
        <td width="6%" style="font-size:10px">PREFIJO</td>
        <td width="11%" align="center">CANTIDAD</td>
        <td width="12%" align="center">HORA</td>
        <td width="13%" align="center">TIPO</td>
        <td width="25%" align="center">ACCIÓN</td>
	</tr>
    <?php
    $y=0;
    $z=count($hipodomo);
    if ($z>0 && $hipodomo[0]!="") {
        foreach ($hipodomo as $hip) {?>
			<tr class="brillo" style="font-size:16px;border-bottom:1px solid #D5D5D5">
			  <td><?php echo $hip ?></td>
			  <td align="center"><?php echo $pre[$y]; ?></td>
			  <td align="center"><?php echo $cantidad[$y]." Carreras"; ?></td>
				<td align="center"><?php echo $horainicio[$y]; ?></td>
				<td align="center"><?php echo $tipocarrera[$y]; ?></td>
				<td align="right">
                <?php
                if ($hip!="" && $cod_hipodromo[$y]>0) {
                    $cta=0;
                    $nom_hipodromo=buscaHip4($cod_hipodromo[$y]);
                    for ($i = 1; $i <= $cantidad[$y]; $i++) {
                        $existe=verificarCarrera($nom_hipodromo, $i, $hoy);
                        if ($existe==1) {
                            $cta++;
                        }
                    }
                    if ($cta!=$cantidad[$y]) {?>
                        <div align="center" style="height:38px; width:100%;" id="divAccion<?php echo $y; ?>">
                          <input type="submit" id="botAccion<?php echo $y; ?>" 
                            class="btn btn-danger"
                            onClick="crearCarrera('<?php echo $cantidad[$y]; ?>',
                            '<?php echo $pre[$y]; ?>',
                            '<?php echo $Horses[$y]; ?>',
                            '<?php echo $cod_hipodromo[$y]; ?>',
                            '#divAccion<?php echo $y; ?>',
                            '<?php echo $z; ?>');"
                            style="padding:4px 0px 0px 0px; height:37px;width:156px; font-size:16px; text-decoration:none;background: #C6F;"
                            value="Crear carreras" 
                            title=" se crearán <?php echo $cantidad[$y]?> carreras &#13; para el hipódromo <?php echo $hip ?>"/>
                      </div>
					<?php
                    } else {?>
                    	<div align="center" style="height:29px;width:100%;padding:9px 0px 0px 0px;color:#009900">
                        	CARRERAS YA CREADAS
                        </div>
					<?php
                    }
                } else {?>
						<div align="center" style="height:38px; width:100%;">
						<a class="btn btn-danger" href="hipodromos_listas.php"  
                        style="text-align:center; color:#FFFFFF; width:135px;text-decoration:none; font-size:12px"
                        title="Hipodromo no existe o no configurado para TWINSPIRES">
  							<i class="fa fa-cog fa-2x pull-center"></i> IR A HIPÓDROMOS
                        </a>
						</div>
					<?php
                }
                ?>  
				</td>
			</tr>
		<?php
            $y++;
        }
    } else {?>
        <tr style="text-align:center; font-size:28px; height:100px">
            <td colspan="6">NO EXISTEN DATOS</td>
        </tr>
    	<?php
    }?>        
</table>