<?php
require_once('../Connections/conexionbanca.php');
 
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
if (!isset($_SESSION)) {
    session_start();
} require_once('../Connections/conexionbanca.php');
set_time_limit(0);







$fech=fechaactualbd();
$horasistema=horaactual();
    

$query_Recordset1 = sprintf(
        "/* PARSEADORES1 includes\racebets_dividendos.php - QUERY 1 */ SELECT * FROM carrera ca, 
hipodromo hi
WHERE  
ca.fec_carrera=%s AND 
ca.est_confirmacion = 1 AND
ca.est_carrera = 0 AND
ca.cod_racebets > 0 AND
ca.cod_hipodromo=hi.cod_hipodromo AND 
hi.mtp_racebets=1 
ORDER BY hor_carrera",
        GetSQLValueString($fech, "date")
    );
    $Recordset1 = mysqli_query($conexionbanca, $query_Recordset1) or die(mysqli_error($conexionbanca));
    $row_Recordset1 = mysqli_fetch_assoc($Recordset1);
    $totalRows_Recordset1 = mysqli_num_rows($Recordset1);
echo $totalRows_Recordset1.' totalRows_Recordset1<br>';

$cookieracebets="cookie: rbset=^%^7B^%^22dialog^%^22^%^3A^%^7B^%^22general^%^22^%^3A^%^7B^%^22language^%^22^%^3A^%^22es^%^22^%^7D^%^7D^%^7D; Acquisition_Status_Current=Prospect; Start_Acquisition=Prospect; Client_Status_Current=Prospect; Start_Client_Status=Prospect; Customer_Level=PC; _gcl_au=1.1.2000492430.1677634427; _ga=GA1.2.1004048035.1677634428; _gid=GA1.2.2099047884.1677634428; language=es; OptanonAlertBoxClosed=2023-03-01T10:02:33.047Z; CONSENT=^%^7B^%^22functional^%^22^%^3A1^%^2C^%^22marketing^%^22^%^3A1^%^2C^%^22performance^%^22^%^3A1^%^2C^%^22targeting^%^22^%^3A1^%^7D; _fbp=fb.1.1677664954172.1114991864; _xpid=1389816485; _xpkey=tEzwhhqr4Yy1TQXGrq5739SR1Ft4DN9g; _hjSessionUser_447710=eyJpZCI6IjAwMDkxMDU1LTgzNTgtNWM2My05YzBiLTQ3MmU3YmRjYTA1MSIsImNyZWF0ZWQiOjE2Nzc2NjQ5NTM3NjgsImV4aXN0aW5nIjp0cnVlfQ==; rbsid=emsttru3oapram34oubjvs6r92; rbssn=^%^7B^%^22sidebar^%^22^%^3A^%^7B^%^22activeTab^%^22^%^3A^%^22current^%^22^%^2C^%^22filters^%^22^%^3A^%^5B^%^22G^%^22^%^2C^%^22J^%^22^%^2C^%^22T^%^22^%^5D^%^2C^%^22antePostFilter^%^22^%^3A^%^22general^%^22^%^2C^%^22current^%^22^%^3A^%^5B^%^5D^%^2C^%^22antepost^%^22^%^3A^%^5B^%^5D^%^2C^%^22date^%^22^%^3A^%^5B^%^5D^%^2C^%^22expires^%^22^%^3A1677902400000^%^7D^%^7D; Initdone=1; Orientation=0; _hjIncludedInSessionSample_447710=1; _hjSession_447710=eyJpZCI6IjFmMWY4YTFkLTcwYzUtNDMyOS04YWUwLWJlNDNlNmY2YzNiMCIsImNyZWF0ZWQiOjE2Nzc4NDA5MzUxNjAsImluU2FtcGxlIjp0cnVlfQ==; _hjIncludedInPageviewSample=1; _hjAbsoluteSessionInProgress=0; _dc_gtm_UA-6328226-1=1; OptanonConsent=isIABGlobal=false&datestamp=Fri+Mar+03+2023+07^%^3A25^%^3A51+GMT-0400+(hora+de+Venezuela)&version=6.39.0&hosts=&landingPath=NotLandingPage&groups=C0001^%^3A1^%^2CC0003^%^3A1^%^2CC0002^%^3A1^%^2CC0004^%^3A1&geolocation=VE^%^3BV&AwaitingReconsent=false; XSRF-TOKEN=dd228^%^3B1677842761^%^3B8face0e075ea13c7f3f9014d5ac8ff5a; AWSALBTG=ikP5mj3xegJz6cb3UEiOMbBTiFUGdc7SBhz97E0VlhRF4TgFaiZMup8MZe212P6b/TlBEUNDeJvBojq7qyZREOl+UmSLVkyXo969ydQ9csA/XhkfJ2SpRaaFGN6Pr0dIrQ+YeXkPFOPPHDet58LXMMd21b19hkdcQrl7YXiQky5Tia0Zh/4=; AWSALB=aSsbEONnNf2X1Pq0EF1gLpHkru2fGsn++bdg8SvRchrepbwfGYz/DvqtlMVZd2z+XbvSUm8JTgkUJdDs732NBmoltLuJznImUFASCTWqp5I4ydVvUwV/JqrXUp6KtzU8JEVU/pYx18/LYtIdlXpfvwzg0RmcDZj1TPK2wkmmR/ZFs2rQmqFWQERsENmXDg==";

if ($totalRows_Recordset1>0) {
    $t=0;
    
    do {







// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://www.racebets.com/ajax/races/details/id/'.$row_Recordset1['cod_racebets']);
//curl_setopt($ch, CURLOPT_URL, 'https://www.racebets.com/ajax/races/details/id/5777317');//normal
//curl_setopt($ch, CURLOPT_URL, 'https://www.racebets.com/ajax/races/details/id/5774930'); //empate primer lugar
//curl_setopt($ch, CURLOPT_URL, 'https://www.racebets.com/ajax/races/details/id/5764562');//empate segundo lugar 
//curl_setopt($ch, CURLOPT_URL, 'https://www.racebets.com/ajax/races/details/id/5764566');//empate tercel lugar 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: www.racebets.com';
$headers[] = 'Pragma: no-cache';
$headers[] = 'Cache-Control: no-cache';
$headers[] = 'Sec-Ch-Ua: ^^';
$headers[] = 'Accept: */*';
$headers[] = 'X-Xsrf-Token: dd228;1677842761;8face0e075ea13c7f3f9014d5ac8ff5a';
$headers[] = 'X-Requested-With: XMLHttpRequest';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Windows^^\"\"';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Referer: https://www.racebets.com/es/carreras-de-caballos/race/details/id/5777317/';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cookie: rbset=^%^7B^%^22dialog^%^22^%^3A^%^7B^%^22general^%^22^%^3A^%^7B^%^22language^%^22^%^3A^%^22es^%^22^%^7D^%^7D^%^7D; Acquisition_Status_Current=Prospect; Start_Acquisition=Prospect; Client_Status_Current=Prospect; Start_Client_Status=Prospect; Customer_Level=PC; _gcl_au=1.1.2000492430.1677634427; _ga=GA1.2.1004048035.1677634428; _gid=GA1.2.2099047884.1677634428; language=es; OptanonAlertBoxClosed=2023-03-01T10:02:33.047Z; CONSENT=^%^7B^%^22functional^%^22^%^3A1^%^2C^%^22marketing^%^22^%^3A1^%^2C^%^22performance^%^22^%^3A1^%^2C^%^22targeting^%^22^%^3A1^%^7D; _fbp=fb.1.1677664954172.1114991864; _xpid=1389816485; _xpkey=tEzwhhqr4Yy1TQXGrq5739SR1Ft4DN9g; _hjSessionUser_447710=eyJpZCI6IjAwMDkxMDU1LTgzNTgtNWM2My05YzBiLTQ3MmU3YmRjYTA1MSIsImNyZWF0ZWQiOjE2Nzc2NjQ5NTM3NjgsImV4aXN0aW5nIjp0cnVlfQ==; rbsid=emsttru3oapram34oubjvs6r92; rbssn=^%^7B^%^22sidebar^%^22^%^3A^%^7B^%^22activeTab^%^22^%^3A^%^22current^%^22^%^2C^%^22filters^%^22^%^3A^%^5B^%^22G^%^22^%^2C^%^22J^%^22^%^2C^%^22T^%^22^%^5D^%^2C^%^22antePostFilter^%^22^%^3A^%^22general^%^22^%^2C^%^22current^%^22^%^3A^%^5B^%^5D^%^2C^%^22antepost^%^22^%^3A^%^5B^%^5D^%^2C^%^22date^%^22^%^3A^%^5B^%^5D^%^2C^%^22expires^%^22^%^3A1677902400000^%^7D^%^7D; Initdone=1; Orientation=0; _hjIncludedInSessionSample_447710=1; _hjSession_447710=eyJpZCI6IjFmMWY4YTFkLTcwYzUtNDMyOS04YWUwLWJlNDNlNmY2YzNiMCIsImNyZWF0ZWQiOjE2Nzc4NDA5MzUxNjAsImluU2FtcGxlIjp0cnVlfQ==; _hjIncludedInPageviewSample=1; _hjAbsoluteSessionInProgress=0; _dc_gtm_UA-6328226-1=1; OptanonConsent=isIABGlobal=false&datestamp=Fri+Mar+03+2023+07^%^3A25^%^3A51+GMT-0400+(hora+de+Venezuela)&version=6.39.0&hosts=&landingPath=NotLandingPage&groups=C0001^%^3A1^%^2CC0003^%^3A1^%^2CC0002^%^3A1^%^2CC0004^%^3A1&geolocation=VE^%^3BV&AwaitingReconsent=false; XSRF-TOKEN=dd228^%^3B1677842761^%^3B8face0e075ea13c7f3f9014d5ac8ff5a; AWSALBTG=ikP5mj3xegJz6cb3UEiOMbBTiFUGdc7SBhz97E0VlhRF4TgFaiZMup8MZe212P6b/TlBEUNDeJvBojq7qyZREOl+UmSLVkyXo969ydQ9csA/XhkfJ2SpRaaFGN6Pr0dIrQ+YeXkPFOPPHDet58LXMMd21b19hkdcQrl7YXiQky5Tia0Zh/4=; AWSALB=aSsbEONnNf2X1Pq0EF1gLpHkru2fGsn++bdg8SvRchrepbwfGYz/DvqtlMVZd2z+XbvSUm8JTgkUJdDs732NBmoltLuJznImUFASCTWqp5I4ydVvUwV/JqrXUp6KtzU8JEVU/pYx18/LYtIdlXpfvwzg0RmcDZj1TPK2wkmmR/ZFs2rQmqFWQERsENmXDg==';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo '<br><br>';

$fulldatos = json_decode($result, true);


echo '<br><br>';
$EX=0;
$EXx=0;
$EXxx=0;
$EXxxx=0;
$TR=0;
$TRx=0;
$TRxx=0;
$TRxxx=0;
$SP=0;
$SPx=0;
$SPxx=0;
$SPxxx=0;
$vul=0;
foreach ($fulldatos["result"]["odds"]["other"] as $exoticas){
if(array_key_exists('EXA', $fulldatos["result"]["odds"]["other"][$vul])) {  foreach ($fulldatos["result"]["odds"]["other"][$vul]["EXA"] as $divEXA => $ncEXA){
if($EX==0){$ord_exacta=str_replace('-', '/', $ncEXA[0]); $div_exacta=$divEXA*2;$EXx++;}
if($EX==1){$ord_exacta_doble=str_replace('-', '/', $ncEXA[0]); $div_exacta_doble=$divEXA*2;$EXxx++;}
if($EX==2){$ord_exacta_triple=str_replace('-', '/', $ncEXA[0]); $div_exacta_triple=$divEXA*2;$EXxxx++;}
if($EXx==1){$EX++;} if ($EXxx==1){$EX++;} if ($EXxxx==1){$EX++;}}}


if(array_key_exists('TRI', $fulldatos["result"]["odds"]["other"][$vul])) {  foreach ($fulldatos["result"]["odds"]["other"][$vul]["TRI"] as $divTRI => $ncTRI){
if($TR==0){$ord_trifecta=str_replace('-', '/', $ncTRI[0]); $div_trifecta=$divTRI/2;$TRx++;}
if($TR==1){$ord_trifecta_doble=str_replace('-', '/', $ncTRI[0]); $div_trifecta_doble=$divTRI/2;$TRxx++;}
if($TR==2){$ord_trifecta_triple=str_replace('-', '/', $ncTRI[0]); $div_trifecta_triple=$divTRI/2;$TRxxx++;}
if($TRx==1){$TR++;} if ($TRxx==1){$TR++;} if ($TRxxx==1){$TR++;}}}

if(array_key_exists('SFC', $fulldatos["result"]["odds"]["other"][$vul])) {  foreach ($fulldatos["result"]["odds"]["other"][$vul]["SFC"] as $divSFC => $ncSFC){
if($SP==0){$ord_superfecta=str_replace('-', '/', $ncSFC[0]); $div_superfecta=$divSFC/10;$SPx++;}
if($SP==1){$ord_superfecta_doble=str_replace('-', '/', $ncSFC[0]); $div_superfecta_doble=$divSFC/10;$SPxx++;}
if($SP==2){$ord_superfecta_triple=str_replace('-', '/', $ncSFC[0]); $div_superfecta_triple=$divSFC/10;$SPxxx++;}
if($SPx==1){$SP++;} if ($SPxx==1){$SP++;} if ($SPxxx==1){$SP++;}}}

$vul++;  }



echo '<br><br>';
$PO=0;$PO1=0;$PO2=0;$PO3=0;$PO4=0;
foreach ($fulldatos["result"]["positions"] as $positionskey => $positionsdat){
if($positionsdat["position"]==1 && $PO1==0){ $eje_primero=$positionsdat["programNumber"];}
if($positionsdat["position"]==1 && $PO1==1){ $eje_doble_primero=$positionsdat["programNumber"];}
if($positionsdat["position"]==1 && $PO1==2){ $eje_triple_primero=$positionsdat["programNumber"];}
if (isset($eje_primero)){if($PO1==0){$PO1++;}} if (isset($eje_doble_primero)){if($PO1==1){$PO1++;}} if (isset($eje_triple_primero)){if($PO1==2){$PO1++;}} 
if($positionsdat["position"]==2 && $PO2==0){ $eje_segundo=$positionsdat["programNumber"];}
if($positionsdat["position"]==2 && $PO2==1){ $eje_doble_segundo=$positionsdat["programNumber"];}
if($positionsdat["position"]==2 && $PO2==2){ $eje_triple_segundo=$positionsdat["programNumber"];}
if (isset($eje_segundo)){if($PO2==0){$PO2++;}} if (isset($eje_doble_segundo)){if($PO2==1){$PO2++;}} if (isset($eje_triple_segundo)){if($PO2==2){$PO2++;}} 
if($positionsdat["position"]==3 && $PO3==0){ $eje_tercero=$positionsdat["programNumber"];}
if($positionsdat["position"]==3 && $PO3==1){ $eje_doble_tercero=$positionsdat["programNumber"];}
if($positionsdat["position"]==3 && $PO3==2){ $eje_triple_tercero=$positionsdat["programNumber"];}
if (isset($eje_tercero)){if($PO3==0){$PO3++;}} if (isset($eje_doble_tercero)){if($PO3==1){$PO3++;}} if (isset($eje_triple_tercero)){if($PO3==2){$PO3++;}} 
if($positionsdat["position"]==4 && $PO4==0){ $eje_cuarto=$positionsdat["programNumber"];}
if($positionsdat["position"]==4 && $PO4==1){ $eje_doble_cuarto=$positionsdat["programNumber"];}
if($positionsdat["position"]==4 && $PO4==2){ $eje_triple_cuarto=$positionsdat["programNumber"];}
if (isset($eje_cuarto)){if($PO4==0){$PO4++;}} if (isset($eje_doble_cuarto)){if($PO4==1){$PO4++;}} if (isset($eje_triple_cuarto)){if($PO4==2){$PO4++;}} 
$PO++;}
echo '<br><br>';








$cAct=0;
if (!isset($eje_primero)) {$eje_primero=0;}
if (!isset($eje_doble_primero)) {$eje_doble_primero=0;}
if (!isset($eje_triple_primero)) {$eje_triple_primero=0;}

if (!isset($eje_segundo)) {$eje_segundo=0;}
if (!isset($eje_doble_segundo)) {$eje_doble_segundo=0;}
if (!isset($eje_triple_segundo)) {$eje_triple_segundo=0;}

if (!isset($eje_tercero)) {$eje_tercero=0;}
if (!isset($eje_doble_tercero)) {$eje_doble_tercero=0;}
if (!isset($eje_triple_tercero)) {$eje_triple_tercero=0;}

if (!isset($eje_cuarto)) {$eje_cuarto=0;}
if (!isset($eje_doble_cuarto)) {$eje_doble_cuarto=0;}
if (!isset($eje_triple_cuarto)) {$eje_triple_cuarto=0;}




$W=0;
$P=0;
$S=0;
if (isset($fulldatos["result"]["odds"]["wps"]["WIN"])) {foreach ($fulldatos["result"]["odds"]["wps"]["WIN"] as $ncWIN => $divWIN){
if($ncWIN==$eje_primero){ $div_primero_gan=$divWIN*2;}
if($ncWIN==$eje_doble_primero){ $div_doble_primero_gan=$divWIN*2;}
if($ncWIN==$eje_triple_primero){ $div_triple_primero_gan=$divWIN*2;}

}}

if (isset($fulldatos["result"]["odds"]["wps"]["PLC"])) {foreach ($fulldatos["result"]["odds"]["wps"]["PLC"] as $ncPLC => $divPLC){
if($ncPLC==$eje_primero){ $div_primero_pla=$divPLC*2;}
if($ncPLC==$eje_doble_primero){ $div_doble_primero_pla=$divPLC*2;}
if($ncPLC==$eje_triple_primero){ $div_triple_primero_pla=$divPLC*2;}

if($ncPLC==$eje_segundo){ $div_segundo_pla=$divPLC*2;}
if($ncPLC==$eje_doble_segundo){ $div_doble_segundo_pla=$divPLC*2;}
if($ncPLC==$eje_triple_segundo){ $div_triple_segundo_pla=$divPLC*2;}


}}

if (isset($fulldatos["result"]["odds"]["wps"]["SHW"])) {foreach ($fulldatos["result"]["odds"]["wps"]["SHW"] as $ncSHW => $divSHW){
if($ncSHW==$eje_primero){ $div_primero_sho=$divSHW*2;}
if($ncSHW==$eje_doble_primero){ $div_doble_primero_sho=$divSHW*2;}
if($ncSHW==$eje_triple_primero){ $div_triple_primero_sho=$divSHW*2;}

if($ncSHW==$eje_segundo){ $div_segundo_sho=$divSHW*2;}
if($ncSHW==$eje_doble_segundo){ $div_doble_segundo_sho=$divSHW*2;}
if($ncSHW==$eje_triple_segundo){ $div_segundo_shoTriple=$divSHW*2;}

if($ncSHW==$eje_tercero){ $div_tercero_sho=$divSHW*2;}
if($ncSHW==$eje_doble_tercero){ $div_doble_tercero_sho=$divSHW*2;}
if($ncSHW==$eje_triple_tercero){ $div_triple_tercero_sho=$divSHW*2;}

}}


 echo '<br><br>';


if (!isset($div_primero_gan)) {$div_primero_gan=0;}
if (!isset($div_doble_primero_gan)) {$div_doble_primero_gan=0;}
if (!isset($div_triple_primero_gan)) {$div_triple_primero_gan=0;}

if (!isset($div_primero_pla)) {$div_primero_pla=0;}
if (!isset($div_doble_primero_pla)) {$div_doble_primero_pla=0;}
if (!isset($div_triple_primero_pla)) {$div_triple_primero_pla=0;}

if (!isset($div_primero_sho)) {$div_primero_sho=0;}
if (!isset($div_doble_primero_sho)) {$div_doble_primero_sho=0;}
if (!isset($div_triple_primero_sho)) {$div_triple_primero_sho=0;}

if (!isset($div_segundo_pla)) {$div_segundo_pla=0;}
if (!isset($div_doble_segundo_pla)) {$div_doble_segundo_pla=0;}
if (!isset($div_triple_segundo_pla)) {$div_triple_segundo_pla=0;}

if (!isset($div_segundo_sho)) {$div_segundo_sho=0;}
if (!isset($div_doble_segundo_sho)) {$div_doble_segundo_sho=0;}
if (!isset($div_triple_segundo_sho)) {$div_triple_segundo_sho=0;}

if (!isset($div_tercero_sho)) {$div_tercero_sho=0;}
if (!isset($div_doble_tercero_sho)) {$div_doble_tercero_sho=0;}
if (!isset($div_triple_tercero_sho)) {$div_triple_tercero_sho=0;}



//dividendos normales listo
echo 'cAct...=  '.$cAct.'<br>';
echo 'eje_primero...=  '.$eje_primero.', ';//listo
echo 'div_primero_gan...=  '.$div_primero_gan.', ';//listo
echo 'div_primero_pla...=  '.$div_primero_pla.', ';//listo
echo 'div_primero_sho...=  '.$div_primero_sho.', ';//listo
echo '<br>';

echo 'eje_segundo...=  '.$eje_segundo.', ';//listo
echo 'div_segundo_pla...=  '.$div_segundo_pla.', ';//listo
echo 'div_segundo_sho...=  '.$div_segundo_sho.', ';//listo
echo '<br>';

echo 'eje_tercero...=  '.$eje_tercero.', ';//listo
echo 'div_tercero_sho...=  '.$div_tercero_sho.', ';//listo
echo '<br>';

//dividendos doble empate listo

echo 'eje_doble_primero...=  '.$eje_doble_primero.', ';//listo
echo 'div_doble_primero_gan...=  '.$div_doble_primero_gan.', ';//listo
echo 'div_doble_primero_pla...=  '.$div_doble_primero_pla.', ';//listo
echo 'div_doble_primero_sho...=  '.$div_doble_primero_sho.', ';//listo
echo '<br>';

echo 'eje_doble_segundo...=  '.$eje_doble_segundo.', ';//listo
echo 'div_doble_segundo_pla...=  '.$div_doble_segundo_pla.', ';//listo
echo 'div_doble_segundo_sho...=  '.$div_doble_segundo_sho.', ';//listo
echo '<br>';

echo 'eje_doble_tercero...=  '.$eje_doble_tercero.', ';//listo
echo 'div_doble_tercero_sho...=  '.$div_doble_tercero_sho.', ';//listo
echo '<br>';

//dividendos triple empate

echo 'eje_triple_primero...=  '.$eje_triple_primero.', ';
echo 'div_triple_primero_gan...=  '.$div_triple_primero_gan.', ';
echo 'div_triple_primero_pla...=  '.$div_triple_primero_pla.', ';
echo 'div_triple_primero_sho...=  '.$div_triple_primero_sho.', ';
echo '<br>';

echo 'eje_triple_segundo...=  '.$eje_triple_segundo.', ';
echo 'div_triple_segundo_pla...=  '.$div_triple_segundo_pla.', ';
echo 'div_triple_segundo_sho...=  '.$div_triple_segundo_sho.', ';
echo '<br>';

echo 'eje_triple_tercero...=  '.$eje_triple_tercero.', ';
echo 'div_triple_tercero_sho...=  '.$div_triple_tercero_sho.', ';
echo '<br>';


//emparte cuarto lugar
echo 'eje_cuarto...=  '.$eje_cuarto.', ';
echo 'eje_doble_cuarto...=  '.$eje_doble_cuarto.', ';
echo 'eje_triple_cuarto...=  '.$eje_triple_cuarto.', ';
echo '<br>';
// exacta
$fac_exacta=2;
echo 'fac_exacta...=  '.$fac_exacta.', ';
if (!isset($ord_exacta)) {$ord_exacta='0/0';}
echo 'ord_exacta...=  '.$ord_exacta.', ';
if (!isset($div_exacta)) {$div_exacta=0;}
echo 'div_exacta...=  '.$div_exacta.', ';

if (!isset($ord_exacta_doble)) {$ord_exacta_doble='0/0';}
echo 'ord_exacta_doble...=  '.$ord_exacta_doble.', ';
if (!isset($div_exacta_doble)) {$div_exacta_doble=0;}
echo 'div_exacta_doble...=  '.$div_exacta_doble.', ';

if (!isset($ord_exacta_triple)) {$ord_exacta_triple='0/0';}
echo 'ord_exacta_triple...=  '.$ord_exacta_triple.', ';
if (!isset($div_exacta_triple)) {$div_exacta_triple=0;}
echo 'div_exacta_triple...=  '.$div_exacta_triple.', ';
echo '<br>';
// trifecta
$fac_trifecta=0.5;
echo 'fac_trifecta...=  '.$fac_trifecta.', ';
if (!isset($ord_trifecta)) {$ord_trifecta='0/0/0';}
echo 'ord_trifecta...=  '.$ord_trifecta.', ';
if (!isset($div_trifecta)) {$div_trifecta=0;}
echo 'div_trifecta...=  '.$div_trifecta.', ';

if (!isset($ord_trifecta_doble)) {$ord_trifecta_doble='0/0/0';}
echo 'ord_trifecta_doble...=  '.$ord_trifecta_doble.', ';
if (!isset($div_trifecta_doble)) {$div_trifecta_doble=0;}
echo 'div_trifecta_doble...=  '.$div_trifecta_doble.', ';

if (!isset($ord_trifecta_triple)) {$ord_trifecta_triple='0/0/0';}
echo 'ord_trifecta_triple...=  '.$ord_trifecta_triple.', ';
if (!isset($div_trifecta_triple)) {$div_trifecta_triple=0;}
echo 'div_trifecta_triple...=  '.$div_trifecta_triple.', ';
echo '<br>';
// superfecta
$fac_superfecta=0.1;
echo 'fac_superfecta...=  '.$fac_superfecta.', ';
if (!isset($ord_superfecta)) {$ord_superfecta='0/0/0/0';}
echo 'ord_superfecta...=  '.$ord_superfecta.', ';
if (!isset($div_superfecta)) {$div_superfecta=0;}
echo 'div_superfecta...=  '.$div_superfecta.', ';

if (!isset($ord_superfecta_doble)) {$ord_superfecta_doble='0/0/0/0';}
echo 'ord_superfecta_doble...=  '.$ord_superfecta_doble.', ';
if (!isset($div_superfecta_doble)) {$div_superfecta_doble=0;}
echo 'div_superfecta_doble...=  '.$div_superfecta_doble.', ';

if (!isset($ord_superfecta_triple)) {$ord_superfecta_triple='0/0/0/0';}
echo 'ord_superfecta_triple...=  '.$ord_superfecta_triple.', ';
if (!isset($div_superfecta_triple)) {$div_superfecta_triple=0;}
echo 'div_superfecta_triple...=  '.$div_superfecta_triple.', ';
$hconfir=$horasistema;
echo 'hconfir...=  '.$hconfir.'<br>';
$confirmandox=9;
//confirmandox=%s, 9 es confirmado por racebets
//est_confirmacion=%s, no se 0 cuando no se hecho nada 1 cuando se guarda la primera ves 2 cuando se verifica que el que se guardo es el mismo actual
//control_dividendo=%s, no se

$tiempodesdecierre=restahoras($row_Recordset1['hor_carrera'], $horasistema);
echo 'tiempodesdecierre= '.$tiempodesdecierre.'<br>';
if (($div_exacta>0) OR ($div_primero_gan>0 && $tiempodesdecierre>='00:07:00')){

if($row_Recordset1['control_dividendo']==0) {$control_dividendo=1;}
if ($row_Recordset1['control_dividendo']==1) {
    echo 'empieza la verificacion<br>';
    if ($row_Recordset1['eje_primero']==$eje_primero*1 &&
number_format($row_Recordset1['div_primero_gan'], 2)==number_format(floatval($div_primero_gan), 2) &&
number_format($row_Recordset1['div_primero_pla'], 2)==number_format(floatval($div_primero_pla), 2) &&
number_format($row_Recordset1['div_primero_sho'], 2)==number_format(floatval($div_primero_sho), 2) &&
$row_Recordset1['eje_segundo']==$eje_segundo*1 &&
number_format($row_Recordset1['div_segundo_pla'], 2)==number_format(floatval($div_segundo_pla), 2) &&
number_format($row_Recordset1['div_segundo_sho'], 2)==number_format(floatval($div_segundo_sho), 2) &&
$row_Recordset1['eje_tercero']==$eje_tercero*1 &&
number_format($row_Recordset1['div_tercero_sho'], 2)==number_format(floatval($div_tercero_sho), 2) &&
$row_Recordset1['eje_doble_primero']==$eje_doble_primero*1 &&
number_format($row_Recordset1['div_doble_primero_gan'], 2)==number_format(floatval($div_doble_primero_gan), 2) &&
number_format($row_Recordset1['div_doble_primero_pla'], 2)==number_format(floatval($div_doble_primero_pla), 2) &&
number_format($row_Recordset1['div_doble_primero_sho'], 2)==number_format(floatval($div_doble_primero_sho), 2) &&
$row_Recordset1['eje_doble_segundo']==$eje_doble_segundo*1 &&
number_format($row_Recordset1['div_doble_segundo_pla'], 2)==number_format(floatval($div_doble_segundo_pla), 2) &&
number_format($row_Recordset1['div_doble_segundo_sho'], 2)==number_format(floatval($div_doble_segundo_sho), 2) &&
$row_Recordset1['eje_doble_tercero']==$eje_doble_tercero*1 &&
number_format($row_Recordset1['div_doble_tercero_sho'], 2)==number_format(floatval($div_doble_tercero_sho), 2) &&
$row_Recordset1['eje_triple_primero']==$eje_triple_primero*1 &&
number_format($row_Recordset1['div_triple_primero_gan'], 2)==number_format(floatval($div_triple_primero_gan), 2) &&
number_format($row_Recordset1['div_triple_primero_pla'], 2)==number_format(floatval($div_triple_primero_pla), 2) &&
number_format($row_Recordset1['div_triple_primero_sho'], 2)==number_format(floatval($div_triple_primero_sho), 2) &&
$row_Recordset1['eje_triple_segundo']==$eje_triple_segundo*1 &&
number_format($row_Recordset1['div_triple_segundo_pla'], 2)==number_format(floatval($div_triple_segundo_pla), 2) &&
number_format($row_Recordset1['div_triple_segundo_sho'], 2)==number_format(floatval($div_triple_segundo_sho), 2) &&
$row_Recordset1['eje_triple_tercero']==$eje_triple_tercero*1 &&
number_format($row_Recordset1['div_triple_tercero_sho'], 2)==number_format(floatval($div_triple_tercero_sho), 2) &&
$row_Recordset1['eje_cuarto']==$eje_cuarto*1 &&
number_format($row_Recordset1['div_exacta'], 2)==number_format(floatval($div_exacta), 2) &&
number_format($row_Recordset1['fac_exacta'], 2)==number_format(floatval($fac_exacta), 2) &&
number_format($row_Recordset1['div_trifecta'], 2)==number_format(floatval($div_trifecta), 2) &&
number_format($row_Recordset1['fac_trifecta'], 2)==number_format(floatval($fac_trifecta), 2) &&
number_format($row_Recordset1['div_superfecta'], 2)==number_format(floatval($div_superfecta), 2) &&
number_format($row_Recordset1['fac_superfecta'], 2)==number_format(floatval($fac_superfecta), 2) &&
number_format($row_Recordset1['div_exacta_doble'], 2)==number_format(floatval($div_exacta_doble), 2) &&
number_format($row_Recordset1['div_exacta_triple'], 2)==number_format(floatval($div_exacta_triple), 2) &&
number_format($row_Recordset1['div_trifecta_doble'], 2)==number_format(floatval($div_trifecta_doble), 2) &&
number_format($row_Recordset1['div_trifecta_triple'], 2)==number_format(floatval($div_trifecta_triple), 2) &&
number_format($row_Recordset1['div_superfecta_doble'], 2)==number_format(floatval($div_superfecta_doble), 2) &&
number_format($row_Recordset1['div_superfecta_triple'], 2)==number_format(floatval($div_superfecta_triple), 2) &&
$row_Recordset1['ord_exacta']==trim($ord_exacta) &&
$row_Recordset1['ord_exacta_doble']==trim($ord_exacta_doble) &&
$row_Recordset1['ord_exacta_triple']==trim($ord_exacta_triple) &&
$row_Recordset1['ord_trifecta']==trim($ord_trifecta) &&
$row_Recordset1['ord_trifecta_doble']==trim($ord_trifecta_doble) &&
$row_Recordset1['ord_trifecta_triple']==trim($ord_trifecta_triple) &&
$row_Recordset1['ord_superfecta']==trim($ord_superfecta) &&
$row_Recordset1['ord_superfecta_doble']==trim($ord_superfecta_doble) &&
$row_Recordset1['ord_superfecta_triple']==trim($ord_superfecta_triple)) {
        $control_dividendo=2;
    } else {
        $control_dividendo=1;
        $est_confirmacion=1;
    }
}
if ($row_Recordset1['cod_confirmacion']==1 && $eje1LugarSimple[$hip]>0) {
    $est_confirmacion=1;
} else {
    if ($row_Recordset1['control_dividendo']==2) {
        $est_confirmacion=0;
    } else {
        $est_confirmacion=1;
    }
}
$carrera=$row_Recordset1['nom_hipodromo']." Carr...".$row_Recordset1['num_carrera'];
$cod_carrera=$row_Recordset1['cod_carrera'];
$updateSQL = sprintf(
    "/* PARSEADORES1 includes\racebets_dividendos.php - QUERY 2 */ UPDATE carrera 
SET 
confirmandox=%s,
est_confirmacion=%s,
control_dividendo=%s,
eje_primero=%s, 
div_primero_gan=%s, 
div_primero_pla=%s, 
div_primero_sho=%s, 
eje_segundo=%s, 
div_segundo_pla=%s, 
div_segundo_sho=%s, 
eje_tercero=%s, 
div_tercero_sho=%s, 
eje_doble_primero=%s, 
div_doble_primero_gan=%s, 
div_doble_primero_pla=%s, 
div_doble_primero_sho=%s, 
eje_doble_segundo=%s, 
div_doble_segundo_pla=%s, 
div_doble_segundo_sho=%s, 
eje_doble_tercero=%s, 
div_doble_tercero_sho=%s, 
eje_triple_primero=%s, 
div_triple_primero_gan=%s, 
div_triple_primero_pla=%s, 
div_triple_primero_sho=%s, 
eje_triple_segundo=%s, 
div_triple_segundo_pla=%s, 
div_triple_segundo_sho=%s, 
eje_triple_tercero=%s, 
div_triple_tercero_sho=%s,
eje_cuarto=%s,
div_exacta=%s,
fac_exacta=%s,
div_trifecta=%s,
fac_trifecta=%s,
div_superfecta=%s,
fac_superfecta=%s,
div_exacta_doble=%s,
div_exacta_triple=%s,
div_trifecta_doble=%s,
div_trifecta_triple=%s,
div_superfecta_doble=%s,
div_superfecta_triple=%s,

ord_exacta=%s,
ord_exacta_doble=%s,
ord_exacta_triple=%s,
ord_trifecta=%s,
ord_trifecta_doble=%s,
ord_trifecta_triple=%s,
ord_superfecta=%s,
ord_superfecta_doble=%s,
ord_superfecta_triple=%s,
hconfir=%s

WHERE cod_carrera=%s",
    GetSQLValueString(9, "int"),
    GetSQLValueString($est_confirmacion, "int"),
    GetSQLValueString($control_dividendo, "int"),
    GetSQLValueString($eje_primero, "int"),
    GetSQLValueString($div_primero_gan, "double"),
    GetSQLValueString($div_primero_pla, "double"),
    GetSQLValueString($div_primero_sho, "double"),
    GetSQLValueString($eje_segundo, "int"),
    GetSQLValueString($div_segundo_pla, "double"),
    GetSQLValueString($div_segundo_sho, "double"),
    GetSQLValueString($eje_tercero, "int"),
    GetSQLValueString($div_tercero_sho, "double"),
    GetSQLValueString($eje_doble_primero, "int"),
    GetSQLValueString($div_doble_primero_gan, "double"),
    GetSQLValueString($div_doble_primero_pla, "double"),
    GetSQLValueString($div_doble_primero_sho, "double"),
    GetSQLValueString($eje_doble_segundo, "int"),
    GetSQLValueString($div_doble_segundo_pla, "double"),
    GetSQLValueString($div_doble_segundo_sho, "double"),
    GetSQLValueString($eje_doble_tercero, "int"),
    GetSQLValueString($div_doble_tercero_sho, "double"),
    GetSQLValueString($eje_triple_primero, "int"),
    GetSQLValueString($div_triple_primero_gan, "double"),
    GetSQLValueString($div_triple_primero_pla, "double"),
    GetSQLValueString($div_triple_primero_sho, "double"),
    GetSQLValueString($eje_triple_segundo, "int"),
    GetSQLValueString($div_triple_segundo_pla, "double"),
    GetSQLValueString($div_triple_segundo_sho, "double"),
    GetSQLValueString($eje_triple_tercero, "int"),
    GetSQLValueString($div_triple_tercero_sho, "double"),
    GetSQLValueString($eje_cuarto, "int"),
    GetSQLValueString($div_exacta, "double"),
    GetSQLValueString($fac_exacta, "double"),
    GetSQLValueString($div_trifecta, "double"),
    GetSQLValueString($fac_trifecta, "double"),
    GetSQLValueString($div_superfecta, "double"),
    GetSQLValueString($fac_superfecta, "double"),
    GetSQLValueString($div_exacta_doble, "double"),
    GetSQLValueString($div_exacta_triple, "double"),
    GetSQLValueString($div_trifecta_doble, "double"),
    GetSQLValueString($div_trifecta_triple, "double"),
    GetSQLValueString($div_superfecta_doble, "double"),
    GetSQLValueString($div_superfecta_triple, "double"),
    GetSQLValueString($ord_exacta, "text"),
    GetSQLValueString($ord_exacta_doble, "text"),
    GetSQLValueString($ord_exacta_triple, "text"),
    GetSQLValueString($ord_trifecta, "text"),
    GetSQLValueString($ord_trifecta_doble, "text"),
    GetSQLValueString($ord_trifecta_triple, "text"),
    GetSQLValueString($ord_superfecta, "text"),
    GetSQLValueString($ord_superfecta_doble, "text"),
    GetSQLValueString($ord_superfecta_triple, "text"),
    GetSQLValueString($hconfir, "date"),
    GetSQLValueString($row_Recordset1['cod_carrera'], "int")
);
$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));


if ($est_confirmacion==1) {
    $insertSQL = sprintf(
        "/* PARSEADORES1 includes\racebets_dividendos.php - QUERY 3 */ INSERT INTO quiencierrayabre 
        (codcarrera, 
        fechaquien, 
        que) 
        VALUES (%s, %s, %s)",
        GetSQLValueString($row_Recordset1['cod_carrera'], "int"),
        GetSQLValueString($fech, "date"),
        GetSQLValueString(51, "int")
    );
    $Result1 = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca)); }


                        if ($est_confirmacion==0) {
    $insertSQL = sprintf(
        "/* PARSEADORES1 includes\racebets_dividendos.php - QUERY 4 */ INSERT INTO quiencierrayabre 
        (codcarrera, 
        fechaquien, 
        que) 
        VALUES (%s, %s, %s)",
        GetSQLValueString($row_Recordset1['cod_carrera'], "int"),
        GetSQLValueString($fech, "date"),
        GetSQLValueString(52, "int")
    );
    $Result1 = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));



                            $tipoProceso=2;
                            include("procesar_resultados_tickets_ame.php");
                            echo "<h3><font color='#027BAD'>Proceso de cálculo culminado! ".$carrera."</font></h3>";
                        }
















}
} while ($row_Recordset1 = mysqli_fetch_assoc($Recordset1));
    
mysqli_free_result($Recordset1);
}