       <?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://service.tvg.com/graph/v2/query');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 30);
curl_setopt($ch, CURLOPT_POSTFIELDS, "^{^^operationName^^\":^^\"getRacesMtpStatus^^\",^^\"variables^^\":^{^^\"wagerProfile^^\":^^\"PORT-Generic^^\",^^\"filterBy^^\":^{^^\"status^^\":^[^^\"MO^^\",^^\"O^^\",^^\"SK^^\",^^\"IC^^\"^],^^\"allRaceClasses^^\":true,^^\"startIn^^\":60^},^^\"sortBy^^\":^{^^\"byPostTime^^\":^^\"ASC^^\"^},^^\"filterByRO^^\":^{^^\"allRaceClasses^^\":true,^^\"status^^\":^[^^\"RO^^\"^]^},^^\"sortByRO^^\":^{^^\"byPostTime^^\":^^\"DESC^^\"^},^^\"pageRO^^\":^{^^\"results^^\":30,^^\"current^^\":0^}^},^^\"query^^\":^^\"query");
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: service.tvg.com';
$headers[] = 'Sec-Ch-Ua: ^^';
$headers[] = 'Accept: */*';
$headers[] = 'Content-Type: application/json';
$headers[] = 'X-Tvg-Context: touch3-tvg';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Origin: https://www.tvg.com';
$headers[] = 'Sec-Fetch-Site: same-site';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Referer: https://www.tvg.com/';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cookie: bid=dd75bab14e3b; _ga=GA1.2.2086726745.1655478297; _gid=GA1.2.1183954545.1655478297; _gcl_au=1.1.249470280.1655478297; pxcts=18064fd2-ee4f-11ec-ad12-486f49587761; _pxvid=180643b5-ee4f-11ec-ad12-486f49587761; _uetsid=de02afc0ee4e11ec94b2ddca85fa1312; _uetvid=de02f550ee4e11ec8a76d9c120ca832c; _fbp=fb.1.1655478305119.312172659; TVG_favorite_tracks=; _px3=624923c3f9d4dfbe27a0cdce7d4944cad5a2a4f49fb0c760f7bbc06b165946d5:kPXIh2kd7xdPxJ0IlK9H8ST7EkYaVqtEqPuJ1yjonIEPUPGZM1eUYNE3O+Ci3hzq+ewaR7/Dwb16W/H/6OMKhA==:1000:8eJNX1JdR0nDGEFVFYbzPri/154yqNGtsIKNQRQ6ERbf+Kx7joyFUoUR0Pr+37jUSUTuUePUk+Skhxl2tW05nUC3hGuBI0+wsBuQaUX++mH5MznyO79QXXf+mzvV5mKVlyjl6OePc9LzrTQpL4kTXiVN0vBTeu6Ln5BZDsvNUpfCsGETCexIBIMvnsjSAxW9etk1o5pjPsPaDtHDzJbazQ==; _clck=n2r1go^|1^|f2e^|0; _qubitTracker=l7hs5o5gw5c-0l4il1juv-wneapog; _gat=1; acqOverLayShown=true; _rdt_uuid=1655478311201.41c81d34-3b71-44e7-ae45-cad7d54ffaa2; qb_generic=:YFyMlfF:.tvg.com; _scid=b761dc61-959d-4435-a479-edb2feb73cad; qb_session=1:1:11:FVYy=B&FkTr=B&FkgP=B:0:YFyMmIX:0:0:0:0:.tvg.com; qb_permanent=l7hs5o5gw5c-0l4il1juv-wneapog:1:1:1:1:0::0:1:0:BirJgp:BirJgp:::::45.190.168.130:coro:14199:venezuela:VE:11.41:-69.67:unknown:unknown:falcon:11475:migrated^|1655478315663:FVYy==B=CcO7=K5&FkTr==B=CjV6=EM&FkgP==B=CkeY=Kx::YFyMmqP:YFyMmIX:0:0:0::0:0:.tvg.com:0; QuantumMetricSessionID=5261e699ec38714bb1efe844f40324fa; QuantumMetricUserID=d080cefe1030433654f9ef2ea75e64c1; _sctr=1^|1655438400000; _pxde=0e88d407ee1f3b41978d898bc904097d26a77acbf7e7bb7b385e0c7026b1ba19:eyJ0aW1lc3RhbXAiOjE2NTU0Nzg0MjY4MjR9; _clsk=5zrl6k^|1655478342813^|2^|0^|j.clarity.ms/collect';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

var_dump($result);