<?php
if (!isset($_SESSION)){session_start();} require_once('../Connections/conexionbanca.php');
$query_Recordset1_alertas = sprintf(
	"/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 1 */ SELECT * FROM 
alertas
WHERE  
idalertas=5",
	GetSQLValueString($fech, "date")
);
$Recordset1_alertas = mysqli_query($conexionbanca, $query_Recordset1_alertas) or die(mysqli_error($conexionbanca));
$row_Recordset1_alertas = mysqli_fetch_assoc($Recordset1_alertas);
$totalRows_Recordset1_alertas = mysqli_num_rows($Recordset1_alertas);
echo $totalRows_Recordset1_alertas.' 333333 '.$row_Recordset1_alertas['activo_archivo'].'<br>';




if($totalRows_Recordset1_alertas>=1 && $row_Recordset1_alertas['activo_archivo']==0){
$fech=fechaactualbd();
$horasistema=horaactual();
$query_Recordset1 = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 2 */ SELECT 
		hi.bus_retirado,
		hi.tip_hipodromo,
		hi.pre_twin,
		hi.nom_hipodromo,
		ca.can_caballos,
		ca.cod_carrera,
		ca.num_carrera		 
	FROM 
		carrera ca, 
		hipodromo hi 
	WHERE
		ca.nom_hipodromo=hi.nom_hipodromo AND
	ca.est_cierre!=3 AND
		ca.est_confirmacion=1 AND
		(hi.bus_retirado=3 OR hi.bus_retirado=4 OR hi.bus_retirado=5 OR hi.bus_retirado=6) AND
		ca.fec_carrera=%s 
		ORDER BY RAND() LIMIT 5",
	GetSQLValueString($fech, "date"));  
$Recordset1 = mysqli_query($conexionbanca, $query_Recordset1) or die(mysqli_error($conexionbanca));
$row_Recordset1 = mysqli_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysqli_num_rows($Recordset1);
echo $totalRows_Recordset1.'...<br>';


$query_Recordset111 = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 3 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);




?>
<div style="background: #096; color: #FFF; width:100%">
    <table width="100%" border="0">
        <tr>
            <td width="464" height="41">HIPODROMO</td>
            <td width="281" align="center">RETIRADOS</td>
        </tr>
    </table>
</div>
<table width="100%" border="1">
    <?php
if ($totalRows_Recordset1>0) {
function consultaTwinRetirados($ncar, $fech, $TrackType, $BrisCode,$cookie,$conexionbanca) {
	$fecUrl=str_replace("-", "", $fech); $retiro=array(); $programados=0;
	if ($TrackType==0) $hType="Thoroughbred";
		else if ($TrackType==1) $hType="Harness";
			else $hType="";
	//$url = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/OddsMtpPost?affid=2800&debug=off&password=Gltbatm&output=json&track='.$BrisCode.'&username=my_sports&race='.$ncar.'&ip=71.212.122.168&cDate='.$fecUrl.'&type='.$hType;
	$url = 'https://www.twinspires.com/adw/todays-tracks/'.$BrisCode.'/'.$hType.'/races/'.$ncar.'/entries?affid=2800';
    //$cookie= 'cookie: _abck=47CE86A7C22EB854B1DD851A67537B34~-1~YAAQZKk2F3Pkf3V8AQAAIVX7ngZmSiD2vbP2N+UXZajSGGniiOnuWQooet75saO0JaFG8NNJ0ONlfhxKW8ksUWXqIN4vGaTmLH5l0yiXBVVkKZy+VicVuPe7AP6KOTBj+k03dmkwipzxeTgJ1hBxYiShRQXHJnbAZNfd/dJbATnWpHJwGvgfmaBvx71npLd/+ucE8I9ZaLyCWouTfapzqHMa6NkuPSen71Fdvjw77veZRm/Pw1Fe4Ejs8wi0lhJriu/Q5RDmJY0rF3ejJyAoLcvZxafFO/NJ4uvmdh1oJ97yN2DNYlVSJ+U2vO2CdONsko1K6868aJdd85TIz8bQ5EF5F7nBZKz+hg/pTHgzWkaorRPstY2bDSkATpClvnG7UDuLq9aIKSpGSo8AnVY=~-1~-1~-1; bm_sz=76130793B2D5BC49CA42327CFE5BA104~YAAQZKk2F3Xkf3V8AQAAIVX7ng3KCEE8GK+6jxWh9hs+0yCgSMx5gQOOGtbCrWLCSqrIUvJIpv8iIVBc3U+yXB02gxKWgND3FoAzLOBBDI8VmsL9Xq4gmVC8H+YJ6OIpSVzdvKHkjSSGq0KNJEzycAtqEst7dU8r4mCqXdrf2YZQY0Q99RFmNOxL0+Kzwh3pa8DfH6xsqANO/7X38yeMV2S4hFA1VB3RWMTxrRGwnJEv698ArWa3UxZATIUFQKr9vxdykUKGIBeujkYGjTLdL7v/4+82EMuDZQA2AcCavfWoVm602zqe~3223605~3225921; ak_bmsc=89EEDDC8C10A6648BFA8D82C2319504C~000000000000000000000000000000~YAAQXHbTF9J4ZJR8AQAA+jqAnw1wvjXrrN5dNcejSFx6p1BpDnv0eD0lEcaFRL27nOuuM+ayJkjtk2gAcmXuq9j67WmaJNLbe8XgkWUorvWX1x8CcIcIucvY5F8xMqnnEdan4P7E1dpBBQ88M5PhpqbuNOVV3NzsgEu53XH1KCDY3OpGFik8yozHM/gUQoGs0naYzV6msQPgnFNGXNGlvbbFeZCSbB28HAy3mRj9Y16Ie7vQiepDOPZykOXjuEd0ZjoMuxZu73TV9zVC0D+317vt0ugpEn4sYavghznVxpeAEhUVGVJRXFhAgAEjP3IhD9sftCPG5oIuQtNDJ+f0HCN34MddXhKhRrHWQ73jaH6fgBuu1ocL/tHDCzWrqeiDaDgR1ifNXjBDlXrmqg==';
echo $url.'<br>';
//include('../cookies/twinspire.php');
     // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
     $ucookiemanual=0;
	 $proxyIP = '54.163.116.201';
$proxyPort = '808';
$proxyUsername = 'linode';
$proxyPassword = 'marca147';


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'twinspirecookie.txt');  $ucookiemanual=1;}
$headers = array();
$headers[] = 'Authority: www.twinspires.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: ^^';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
if($ucookiemanual==0){ $headers[] = $cookie; }
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);



			
			$result2 = curl_exec($ch);
			if (curl_errno($ch)) {
				echo 'Error:' . curl_error($ch);
$updateSQL = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 4 */ UPDATE cookies SET errorcookie=errorcookie+1
WHERE 	id_cookie = 1 AND cookinombre=%s",
GetSQLValueString("twinspire", "text"));
$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
$query_Recordset112 = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 5 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset112 = mysqli_query($conexionbanca, $query_Recordset112) or die(mysqli_error($conexionbanca));
$row_Recordset112 = mysqli_fetch_assoc($Recordset112);
$totalRows_Recordset112 = mysqli_num_rows($Recordset112);
if($row_Recordset112['errorcookie']>5){
    $updateSQL = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 6 */ UPDATE cookies SET errorcookie=errorcookie+1, cookiefull=0
    WHERE 	id_cookie = 1 AND cookinombre=%s",
    GetSQLValueString("twinspire", "text"));
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
}
}
			curl_close($ch);
    
    
    
		//	echo strlen($result2).' <br>';

    
    
    
   // $str_datos = get_url_contents($url); 
	$fulldatos = json_decode($result2,true);
//	echo strlen($fulldatos).' <br>';
	if (isset($fulldatos)) {
		//echo 'estoy aqui<br>';
		$j=0;
		$jno=0;
		$item_details2 = array();

		foreach($fulldatos as $Entriesno) {
			//echo 'estoy aqui<br>';
			//var_dump($Entriesno);
			$programados=$Entriesno["programNumber"];
			//echo $programados.'estoy aqui<br>';
						if ($Entriesno["scratched"]<>"true") {
							$item_details2[]=preg_replace('/[a-zA-Z]/', "",$Entriesno["programNumber"]);
							
						//	echo $Entriesno["programNumber"].' <br>';
							$retirono[$jno]=$Entriesno["programNumber"];
							
							$jno++;
						}
						
					}
					//echo ' <br>';

					//var_dump($item_details2);
					// echo ' <br>';
		foreach($fulldatos as $Entries) {
			
			if ($Entries["scratched"]=="true") {
				$Entries["programNumber"]=preg_replace('/[a-zA-Z]/', "",$Entries["programNumber"]);	
				//echo $Entries["programNumber"].' ret sin verificar<br>';
				if (in_array($Entries["programNumber"], $item_details2)) {}else{ 
					//echo $Entries["programNumber"].' ret ya verificar <br>';
					$retiro[$j]=$Entries["programNumber"];
					$j++;  }
			
			}
			
		}

		








	}
$programados=max(array($programados));
//echo $programados.' PN<br>';
//var_dump($retiro);
//echo '<br>';
//echo '..<br><br>';
	return array($retiro, $programados);
}











	do {
//echo $row_Recordset1['nom_hipodromo'].' <br>';
			if ($row_Recordset1['pre_twin']!="") {
				$ncar=$row_Recordset1['num_carrera'];
				$TrackType=$row_Recordset1['tip_hipodromo'];
				$BrisCode=$row_Recordset1['pre_twin'];
				list($retiro, $cantProgramados)=consultaTwinRetirados($ncar, $fech, $TrackType, $BrisCode,$row_Recordset111['cookiefull'],$conexionbanca);
				if ($cantProgramados!=$row_Recordset1['can_caballos'] && $cantProgramados>3) {
					$cod_carrera=$row_Recordset1['cod_carrera'];
			
					$updateSQL2 = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 7 */ UPDATE carrera SET can_caballos=%s 
										  WHERE cod_carrera=%s",
								GetSQLValueString($cantProgramados, "int"),
								GetSQLValueString($cod_carrera, "int"));
					$Result2 = mysqli_query($conexionbanca, $updateSQL2) or die(mysqli_error($conexionbanca));
			
				
				
				}
				if (isset($retiro[0])) {
					$ejemRetir="-";
					foreach($retiro as $ejem){
						$cod_carrera=$row_Recordset1['cod_carrera'];
						$estado=RetiradosSimple($cod_carrera,$ejem);
						$ejemRetir=$ejemRetir.$ejem."-";
						if ($estado==0) { // retirar caballo
				
							$insertSQL = sprintf("/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 8 */ INSERT INTO retirados 
										(quienretiro, cod_carrera, num_rcaballo) VALUES (%s, %s, %s)",
										GetSQLValueString('twin', "text"),
										 GetSQLValueString($cod_carrera, "int"),
										 GetSQLValueString($ejem, "int"));
							$Result = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));
					
						
						$insertSQL = sprintf(
							"/* PARSEADORES1 includes\twinspires_retirados_v4.php - QUERY 9 */ INSERT INTO quiencierrayabre 
							(codcarrera, 
							fechaquien, 
							que) 
							VALUES (%s, %s, %s)",
							GetSQLValueString($cod_carrera, "int"),
							GetSQLValueString($fech, "date"),
							GetSQLValueString(31, "int")
						);
						$Result1 = mysqli_query($conexionbanca, $insertSQL) or die(mysqli_error($conexionbanca));

						}
					}
					?>
    <tr>
        <td width="464">
            <?php 
								echo $row_Recordset1['nom_hipodromo']." ".trim($row_Recordset1['num_carrera'])." ";
							?>
        </td>
        <td width="281" align="center"><?php echo $ejemRetir; ?></td>
    </tr>
    <?php
				}
			}

	} while ($row_Recordset1 = mysqli_fetch_assoc($Recordset1));
}
mysqli_free_result($Recordset1);
}
?>
</table>