<?php
// 
echo '<br>v10<br>';
error_reporting(E_ALL);
ini_set('display_errors', '1');
//echo "This is a warning error";
//include ("file.php");
// 1 
// 2 Daily Double
// 3 pick 3
// 4 pick 4 
// 5 pick 5
// 6
// 7 
// 8 
// 9
require_once('../Connections/conexionbanca.php');

set_time_limit(0);
$hoy=fechaactualbd();
$horasistema=horaactual();
echo $horasistema.'<br><br><br>';
$totalRows_Recordset1= 0;

$query_Recordset111 = sprintf("/* PARSEADORES1 includes\TwinspireWager.php - QUERY 1 */ SELECT * 
	FROM 
	cookies 
	WHERE
  id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);
	

  $hoy=fechaactualbd();
  $fecUrl=str_replace("-", "", $hoy);
  $urlH = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/CurrentRace?ip=71.212.122.168&affid=2800&debug=off&username=my_sports&password=Gltbatm&output=json';
  
  $ucookiemanual=0;
  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, 'https://www.twinspires.com/adw/todays-tracks?affid=2800&sortOrder=nextUp');
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
  
  curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
  curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
  if(strlen($row_Recordset111['cookiefull'])<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'twinspirecookie.txt');  $ucookiemanual=1;}

  $headers = array();
  $headers[] = 'Authority: www.twinspires.com';
  $headers[] = 'Cache-Control: max-age=0';
  $headers[] = 'Sec-Ch-Ua: ^^';
  $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
  $headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
  $headers[] = 'Upgrade-Insecure-Requests: 1';
  $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
  $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
  $headers[] = 'Sec-Fetch-Site: none';
  $headers[] = 'Sec-Fetch-Mode: navigate';
  $headers[] = 'Sec-Fetch-User: ?1';
  $headers[] = 'Sec-Fetch-Dest: document';
  $headers[] = 'Accept-Language: es-ES,es;q=0.9';
  //$headers[] = 'Cookie: _abck=1289DC72E6C212A2C51A454BD64DDE8A~-1~YAAQnAHorG0WRiSBAQAA6vnMaAjyk8sybXmem0gMglng86nrvBdQrdnoagx6GhXj4xDhLbmy/5Kdgh5q/JbKATk8K6zLjhL7+ttA9TirBunvPmHCe3Oqs/iElskUJ3uBySmHxyEHgEQpX0YdduaFiYm8hmV7SSyMOQN9oHVwl2VRH5VjJKgbpR2ioQUncL6kspNlIzJcPyQOkT1LoaClknIIU2H/ifcJl2v64O23Qw/3dwnwxyrOOq3euA1KO8sMMnoLbhq1oKOM65OQK8oesLP0OTTe1I81T/w3NYT7TW+BiFFwqdCvKQXYEKrKb/9Vzp3jwzRH0Y4fYc4PluIJsPn7687Q/XSEniqQAqbw1WCGpYzIkQxN/WdF2fYDf4AGCCmu/rUEgH4TABcbBt0=~-1~-1~-1; ak_bmsc=BE34077C485C60FA083156B660C33446~000000000000000000000000000000~YAAQnAHorG4WRiSBAQAA6vnMaBBiR9Rlx1KlU/blctiI7Kh862F5JZqxRa3ut6wlIhjWYbglM16+cQy9wXTked1t9PWL6R9HoZ8W6yqpbkjYjoQjSnKSJIgBitTHRVMhZFlXrxQiekO2zjRSAbg8V+3ITJQHLWkxsqatK/khebyCrpI4adVsR8hdSLMZLsw8cA8HrYkepb8uh0PpsCZL5PgKLf0QNd1cPQCIy+ScbtLO9J7Zi8A6Tb4UNHVv+FZg9x35cMgz2O4GfLdHnbHMtR0IQha9ipR3RYwdUFFrR64JKUj9FUwJPLL23r9Dz4UNW20DILqog3hYHdF7jRd3t0SN20sbG/4RGLoiF7D0Yy2b9YXEcLj4Ga2jjATPby4+sDEyj/cWN+0zmFPbUlb44A==; bm_sz=AD1E5CF28066F552CAD338F16345D50D~YAAQnAHorG8WRiSBAQAA6vnMaBCtZs+mak0NrqIKIYRWnPpw1uMm66tFculBrnYkFuj6u9f+OC7Rs7tBWs6o17teBEV3/XyIVckspYvC1y68v3A88sZQq1iWxIDj4Xo/Yhd64epUWLFd80w9CYxd5BoQo0TftFWZ/e6dK8T4RthLPiLAc3oaruxXg/L0J/td07tnPLEgb2dDEeX4aP9RZdPj9ogdVVXa7eyMUaMc9o8ekRtLVlzNHFmp5pbELZ/47QNe8qSGJbsxesE1Jfu9Y/nCqVwY7WLnPbdTnAQ++1tJWGpWJrQl~3356211~3294533';
  if($ucookiemanual==0){ $headers[] = $cookie; }

  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 2);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
  
$fulldatos = json_decode($result,true); 
//var_dump($result);
  
  
$query_Recordset111 = sprintf("SELECT * 
	FROM 
	carrera, hipodromo
	WHERE
  carrera.cod_hipodromo = hipodromo.cod_hipodromo
  AND carrera.fec_carrera  = %s
	AND carrera.TipoApuestas = %s",
    GetSQLValueString($hoy, "date"),
	GetSQLValueString("0", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);
//echo $totalRows_Recordset111.' totalRows_Recordset111<br>';
$pre_twin='';
$pre_twinx=0;
do { 

if (isset($fulldatos)) {

   // echo 'voy aqui <br>';
foreach($fulldatos as $CurrentRace) {
$brisCode=strtoupper($CurrentRace["brisCode"]);
//echo $brisCode.'aaa <br>';
if($row_Recordset111['pre_twin']==$brisCode){
 // echo 'aaa <br>';
 if($row_Recordset111['num_carrera']==1 && $pre_twinx>0){ 
  echo '<br><br><br>';
  }
  echo $row_Recordset111['num_carrera'].' ---- '.$row_Recordset111['nom_hipodromo'];
  echo ' <br>';
///*
  foreach($CurrentRace["races"] as $CurrentRace2) {
if($row_Recordset111['num_carrera']==$CurrentRace2["raceNumber"]){
    echo 'Tipos de apuestas para esta carrera = '.$CurrentRace2["wagers"].' <br>';
    $tapuestas=0;
    $CurrentRace2["wagers"]=preg_replace('/\s+/', '', $CurrentRace2["wagers"]);
    if(strpos(strtoupper($CurrentRace2["wagers"]), 'DAILYDOUBLE') === false){}else{ echo ' Daily Double '; $tapuestas='2'.$tapuestas;}
    if(strpos(strtoupper($CurrentRace2["wagers"]), 'PICK3') === false){}else{ echo ' Pick 3 '; $tapuestas='3'.$tapuestas; }
    if(strpos(strtoupper($CurrentRace2["wagers"]), 'PICK4') === false){}else{ echo ' Pick 4 '; $tapuestas='4'.$tapuestas; }
    if(strpos(strtoupper($CurrentRace2["wagers"]), 'PICK5') === false){}else{ echo ' Pick 5 '; $tapuestas='5'.$tapuestas; }
    echo ' <br>';
    
if($tapuestas>0){
  echo $tapuestas.' <br>';
    $updateSQL = sprintf("UPDATE carrera SET TipoApuestas=%s
    WHERE fec_carrera=%s AND cod_carrera=%s",
    GetSQLValueString($tapuestas, "text"),
    GetSQLValueString($row_Recordset111['fec_carrera'], "date"),
    GetSQLValueString($row_Recordset111['cod_carrera'], "int"));
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
    echo $Result1.' Result1<br>';
  }








 }
  }
//*/
}
  //  $currentRaceNumber=$CurrentRace["currentRaceNumber"];






}


}

if($row_Recordset111['pre_twin']<>$pre_twin){
  if($pre_twinx>=1){ 
//echo '<br><br><br>';
}
}
$pre_twinx++;
$pre_twin=$row_Recordset111['pre_twin'];
} while ($row_Recordset111 = mysqli_fetch_assoc($Recordset111));




