<?php
require_once('../Connections/conexionbanca.php');

set_time_limit(0);
$hoy=fechaactualbd();
$horasistema=horaactual();
echo $horasistema;
$totalRows_Recordset1= 0;
if ($horasistema>'03:20:00' && $horasistema<'20:59:59') {
$updateSQL = sprintf("/* PARSEADORES1 includes\twinspire_programar_carreras_auto_twinsolo2.php - QUERY 1 */ UPDATE alertas SET contadoralerta=contadoralerta+1, hor_alerta=%s, fec_alerta=%s
WHERE idalertas=%s",
GetSQLValueString($horasistema, "date"),
GetSQLValueString($hoy, "date"),
GetSQLValueString(4, "int"));
$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
	
$query_Recordset111 = sprintf("/* PARSEADORES1 includes\twinspire_programar_carreras_auto_twinsolo2.php - QUERY 2 */ SELECT * 
	FROM 
	cookies 
	WHERE
  id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);
	
	//return array($nHi, $dTN, $cCa, $hIn, $tip, $cod_hipodromo, $Horses);

function busHipodromo_twin($identificador) { $hipodromo[0]=0; $hipodromo[1]=-1; $hipodromo[2]=-1; $hipodromo[3]=-1; global $conexionbanca; $query_ConsultaFuncion = sprintf("/* PARSEADORES1 includes\twinspire_programar_carreras_auto_twinsolo2.php - QUERY 3 */ SELECT cod_hipodromo, pro_desde, nom_hipodromo FROM hipodromo WHERE pre_twin = %s LIMIT 1",  GetSQLValueString($identificador, "text")); $ConsultaFuncion = mysqli_query($conexionbanca, $query_ConsultaFuncion) or die(mysqli_error($conexionbanca)); $row_ConsultaFuncion = mysqli_fetch_assoc($ConsultaFuncion); $totalRows_ConsultaFuncion = mysqli_num_rows($ConsultaFuncion); if ($totalRows_ConsultaFuncion>0) {  $hipodromo[0]=1; $hipodromo[1]=$row_ConsultaFuncion['cod_hipodromo']; $hipodromo[2]=$row_ConsultaFuncion['pro_desde'];$hipodromo[3]=$row_ConsultaFuncion['nom_hipodromo']; }   mysqli_free_result($ConsultaFuncion); return $hipodromo; }
function twinspiresPgm($cookie,$conexionbanca){
  $hoy=fechaactualbd();
  $fecUrl=str_replace("-", "", $hoy);
  $urlH = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/CurrentRace?ip=71.212.122.168&affid=2800&debug=off&username=my_sports&password=Gltbatm&output=json';
  
  
  $ucookiemanual=0;
  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $urlH);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'twinspirecookie.txt');  $ucookiemanual=1;}
$headers = array();
$headers[] = 'Authority: www.twinspires.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: ^^Chromium^^\";v=^^\"94^^\",';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
if($ucookiemanual==0){ $headers[] = $cookie; }
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
  
  
  
  
  
  
  
  
  
  
  //$str_datos = get_url_contents($urlH); 
  //$fulldatos = json_decode($str_datos,true); 
  $fulldatos = json_decode($result,true); 

   
  $nHi[0]=""; $dTN[0]=""; $cCa[0]=""; $abb[0]=""; $hIn[0]=""; $tip[0]=""; $cHi[0]="";
  $cod_hipodromo[0]=""; $y=0; $i=0; $z=0; $Horses[0]="";
  $hipHoy=array();$TrackType=array();
  if (isset($fulldatos["CurrentRace"])) {
    foreach($fulldatos["CurrentRace"] as $CurrentRace) {
      $fecCar=explode("T",$CurrentRace["PostTime"]);
      if ($fecCar[0]==$hoy) {
        $hipHoy[$i]=$CurrentRace["BrisCode"];
        $TrackType[$i]=$CurrentRace["TrackType"];
        $i++;
      }
    }
    foreach($hipHoy as $BrisCode) {
      $urlC = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Pgm/Entry?ip=71.212.122.168&affid=2800&debug=off&cDate='.$fecUrl.'&password=Gltbatm&track='.$BrisCode.'&output=json&username=my_sports&type='.$TrackType[$y];
      
      
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $urlC);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3); 
curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'twinspirecookie.txt');  $ucookiemanual=1;}
$headers = array();
$headers[] = 'Authority: www.twinspires.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: ^^Chromium^^\";v=^^\"94^^\",';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
if($ucookiemanual==0){ $headers[] = $cookie; }
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result2 = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
    $updateSQL = sprintf("/* PARSEADORES1 includes\twinspire_programar_carreras_auto_twinsolo2.php - QUERY 4 */ UPDATE cookies SET errorcookie=errorcookie+1
WHERE 	id_cookie = 1 AND cookinombre=%s",
GetSQLValueString("twinspire", "text"));
$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
$query_Recordset112 = sprintf("/* PARSEADORES1 includes\twinspire_programar_carreras_auto_twinsolo2.php - QUERY 5 */ SELECT * 
	FROM 
	cookies 
	WHERE
  id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset112 = mysqli_query($conexionbanca, $query_Recordset112) or die(mysqli_error($conexionbanca));
$row_Recordset112 = mysqli_fetch_assoc($Recordset112);
$totalRows_Recordset112 = mysqli_num_rows($Recordset112);
if($row_Recordset112['errorcookie']>5){
    $updateSQL = sprintf("/* PARSEADORES1 includes\twinspire_programar_carreras_auto_twinsolo2.php - QUERY 6 */ UPDATE cookies SET errorcookie=errorcookie+1, cookiefull=0
    WHERE 	id_cookie = 1 AND cookinombre=%s",
    GetSQLValueString("twinspire", "text"));
    $Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
}
}
curl_close($ch);
      
      
      
      
      
      
      
      
      
      
     // $str_datos = get_url_contents($urlC); 
     // $fulldatos = json_decode($str_datos,true); 
     $fulldatos = json_decode($result2,true); 
	
	
      if (isset($fulldatos["ProgramTracks"]["0"]["DisplayName"])) {
        $nHi[$z]=strtoupper($fulldatos["ProgramTracks"]["0"]["DisplayName"]);
        $dTN[$z]=strtoupper($fulldatos["ProgramTracks"]["0"]["BrisCode"]);
        $tip[$z]=strtoupper($fulldatos["ProgramTracks"]["0"]["Type"]);
		
        $n=strtoupper($fulldatos["ProgramTracks"]["0"]["BrisCode"]); 
        $hi=busHipodromo_twin($n);
        if ($hi[0]!=0) $nHi[$z]=$hi[3];
        $cHi[$z]=$hi[1];
        $cod_hipodromo[$z]=$hi[1]; 
       echo '<br>';
        echo $nHi[$z];
        echo '<br>';
        $hIn[$z]="01:00:00";

        $x=0; 
        foreach($fulldatos["ProgramTracks"]["0"]["Races"] as $Races) {
          $foo =$Races["FullConditions"];

          if ($x==0){ // $Horses[$z]=$cantEjem;
            if (strlen(stristr($foo,'SIMULCAST'))>0) {
              $silmu=1;
              //echo "Se encuentra";
              //echo '<br>';
              $simulcast[$z]=1;
            } else { 
              $silmu=0;
              //echo "no no Se encuentra";
              //echo '<br>';
              $simulcast[$z]=0;
            } 

          } else{ //$Horses[$z].=",".$cantEjem;
            if (strlen(stristr($foo,'SIMULCAST'))>0) {
              $silmu=1;
              //echo "Se encuentra";
              //echo '<br>';
              $simulcast[$z].=",".$silmu;
            } else { 
              $silmu=0;
              //echo "no no Se encuentra";
              //echo '<br>';
              $simulcast[$z].=",".$silmu;
            } 
          }
          
		  $cantEjemx=count($Races["Horses"]);
		  $cantEjemx=$cantEjemx-1;
          $cantEjem=$Races["Horses"][$cantEjemx]["ProgramNumber"];
          if ($x==0) $Horses[$z]=$cantEjem;
          else $Horses[$z].=",".$cantEjem;
          $x++;
        }
        echo '<br>';
        echo $simulcast[$z];
        echo '<br>';
        $cCa[$z]=$x;
		$z++;
      }
      $y++;
    }
  }
  return array($nHi, $dTN, $cCa, $hIn, $tip, $cod_hipodromo, $Horses, $simulcast);
}
list($hipodomo, $pre, $cantidad, $horainicio, $tipocarrera, $cod_hipodromo, $Horses, $simulcast)=twinspiresPgm($row_Recordset111['cookiefull'],$conexionbanca);
// nombre de	prefijo		cantidad	hora de		tipo
// hipodromo 	hipodromo 	carreras	inicio		carrera
?>


<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- InstanceBegin template="/Templates/BaseAdmin.dwt.php" codeOutsideHTMLIsLocked="false" -->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- InstanceBeginEditable name="doctitle" -->
    <title>.:Crear Carera Twins Solo:.</title>

    <!-- InstanceEndEditable -->
    <!-- InstanceBeginEditable name="head" -->
    <!-- InstanceEndEditable -->
    <!--[if lte IE 7]>
<link type="text/css" rel="stylesheet" media="all" href="../css/screen_ie.css" />
<![endif]-->
    <style>
    body {
        background-color: #eeeeee;
        padding: 0;
        margin: 0 auto;
        font-family: "Lucida Grande", Verdana, Arial, "Bitstream Vera Sans", sans-serif;
        font-size: 11px;
    }
    </style>

    <!-- InstanceBeginEditable name="aHead" -->
    <!-- InstanceEndEditable -->
</head>

<body onload="Javascript:history.go(1);" onunload="Javascript:history.go(1);">


    <table width="100%" border="0" cellpadding="0" cellspacing="0"
        style="font-family:'Lucida Grande','Lucida Sans Unicode','Lucida Sans','DejaVu Sans',Verdana,sans-serif;">
        <tr>
            <td height="32" colspan="6">&nbsp;</td>
        </tr>
        <tr style="background: #028A96; color:#FFFFFF; height:30px; text-align:center">
            <td width="32%">HIPODROMO</td>
            <td width="6%" style="font-size:10px">PREFIJO</td>
            <td width="11%" align="center">CANTIDAD</td>
            <td width="12%" align="center">HORA</td>
            <td width="13%" align="center">TIPO</td>
            <td width="25%" align="center">ACCIÓN</td>
        </tr>
        <?php
	$y=0;
	$z=count($hipodomo);
	
	echo $z;
	echo "<br/>";	
	
	if ($z>0 && $hipodomo[0]!="") { 
		foreach($hipodomo as $hip){?>
        <tr class="brillo" style="font-size:16px;border-bottom:1px solid #D5D5D5">
            <td><?php echo $hip ?></td>
            <td align="center"><?php echo $pre[$y]; ?></td>
            <td align="center"><?php echo $cantidad[$y]." Carreras"; ?></td>
            <td align="center"><?php echo $horainicio[$y]; ?></td>
            <td align="center"><?php echo $tipocarrera[$y]; ?></td>
            <td align="right">
                <?php 
				if ($hip!="" && $cod_hipodromo[$y]>0) {
					$cta=0;
					$nom_hipodromo=buscaHip4($cod_hipodromo[$y]);
					for ($i = 1; $i <= $cantidad[$y]; $i++){ $existe=verificarCarrera($nom_hipodromo, $i, $hoy);
						if ($existe==1) $cta++; }
					if ($cta!=$cantidad[$y]) {?>
                <div align="center" style="height:38px; width:100%;" id="divAccion<?php echo $y; ?>">
                    <input type="submit" id="botAccion<?php echo $y; ?>" class="btn btn-danger" onClick="crearCarrera('<?php echo $cantidad[$y]; ?>',
                            '<?php echo $pre[$y]; ?>',
                            '<?php echo $Horses[$y]; ?>',
                            '<?php echo $cod_hipodromo[$y]; ?>',
                            '#divAccion<?php echo $y; ?>',
                            '<?php echo $z; ?>');"
                        style="padding:4px 0px 0px 0px; height:37px;width:156px; font-size:16px; text-decoration:none;background: #C6F;"
                        value="Crear carreras"
                        title=" se crearán <?php echo $cantidad[$y]?> carreras &#13; para el hipódromo <?php echo $hip ?>" />
                </div>
                <?php 
					
$pre=$pre[$y];

$Horses=$Horses[$y];
$cantidad=$cantidad[$y];
$simulcast=$simulcast[$y];
$cod_hipodromo=$cod_hipodromo[$y];

	$url = "http://localhost/includes/programar_carreras_guardar_twinsolo2.php?can=".$cantidad."&horses=".$Horses."&pre=".$pre."&cHip=".$cod_hipodromo."&simulcast=".$simulcast;
    $result = file_get_contents($url);

					
					
					
					
					
					
					
					
					
					} else {?>
                <div align="center" style="height:29px;width:100%;padding:9px 0px 0px 0px;color:#009900">
                    CARRERAS YA CREADAS
                </div>
                <?php
					}
				}
				else {?>
                <div align="center" style="height:38px; width:100%;">
                    <a class="btn btn-danger" href="hipodromos_listas.php"
                        style="text-align:center; color:#FFFFFF; width:135px;text-decoration:none; font-size:12px"
                        title="Hipodromo no existe o no configurado para TWINSPIRES">
                        <i class="fa fa-cog fa-2x pull-center"></i> IR A HIPÓDROMOS
                    </a>
                </div>
                <?php
				}
				?>
            </td>
        </tr>
        <?php 
			$y++;
		}
	}
	else {?>
        <tr style="text-align:center; font-size:28px; height:100px">
            <td colspan="6">NO EXISTEN DATOS</td>
        </tr>
        <?php 
	}?>
    </table>
    <div class="footer"> Copyright © Apuestas Hípicas
        <!-- end .footer -->
    </div>
    <!-- end .container -->
    </div>
</body>
<!-- InstanceEnd -->

</html>
<?php 
	}?>