<?php
 
error_reporting(E_ALL);
ini_set('display_errors', '1');
echo "This is a warning error";
//include ("file.php");


if (!isset($_SESSION)){session_start();} require_once('../Connections/conexionbanca.php');include('../includes/mtp_funcion.php');
// agregue reapertura 
$fechaactual=fechaactualbd();
$query_Recordset1_alertas = sprintf(
	"/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 1 */ SELECT * FROM 
alertas
WHERE  
idalertas=5",
	GetSQLValueString(fechaactualbd(), "date")
);
$Recordset1_alertas = mysqli_query($conexionbanca, $query_Recordset1_alertas) or die(mysqli_error($conexionbanca));
$row_Recordset1_alertas = mysqli_fetch_assoc($Recordset1_alertas);
$totalRows_Recordset1_alertas = mysqli_num_rows($Recordset1_alertas);
//echo $totalRows_Recordset1_alertas.' 333333 '.$row_Recordset1_alertas['activo_archivo'].'<br>';




if($totalRows_Recordset1_alertas>=1 && $row_Recordset1_alertas['activo_archivo']==0){
$query_Recordset111 = sprintf("/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 2 */ SELECT * 
	FROM 
	cookies 
	WHERE
	id_cookie = 1 AND cookinombre = %s
    LIMIT 1",
	GetSQLValueString("twinspire", "text"));   
$Recordset111 = mysqli_query($conexionbanca, $query_Recordset111) or die(mysqli_error($conexionbanca));
$row_Recordset111 = mysqli_fetch_assoc($Recordset111);
$totalRows_Recordset111 = mysqli_num_rows($Recordset111);
//echo $row_Recordset111['cookiefull'];


function consultaCierreTwinspires2($cookie,$conexionbanca) {
	$hipodomo[0]=""; $nombre[0]=""; $horacarr[0]=""; $BrisCode[0]=""; $numeroca[0]=""; $restante[0]=""; $horacier[0]="";
    $url = 'https://www.twinspires.com/php/fw/php_BRIS_BatchAPI/2.3/Tote/CurrentRace?ip=71.212.122.168&affid=2800&debug=off&username=my_sports&password=Gltbatm&output=json';
    
	
	$ucookiemanual=0;
	        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
			$ch = curl_init();

			curl_setopt($ch, CURLOPT_URL, 'https://www.twinspires.com/adw/todays-tracks?affid=2800&sortOrder=nextUp');
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
			
			curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
			curl_setopt($ch, CURLOPT_TIMEOUT, 7); //timeout in seconds
			if(strlen($cookie)<200){ curl_setopt($ch, CURLOPT_COOKIEFILE, 'twinspirecookie.txt');  $ucookiemanual=1;}
	   
			$headers = array();
			$headers[] = 'Authority: www.twinspires.com';
			$headers[] = 'Cache-Control: max-age=0';
			$headers[] = 'Sec-Ch-Ua: ^^';
			$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
			$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
			$headers[] = 'Upgrade-Insecure-Requests: 1';
			$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Mobile Safari/537.36';
			$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
			$headers[] = 'Sec-Fetch-Site: none';
			$headers[] = 'Sec-Fetch-Mode: navigate';
			$headers[] = 'Sec-Fetch-User: ?1';
			$headers[] = 'Sec-Fetch-Dest: document';
			$headers[] = 'Accept-Language: es-ES,es;q=0.9';
			//$headers[] = 'Cookie: _abck=1289DC72E6C212A2C51A454BD64DDE8A~-1~YAAQnAHorG0WRiSBAQAA6vnMaAjyk8sybXmem0gMglng86nrvBdQrdnoagx6GhXj4xDhLbmy/5Kdgh5q/JbKATk8K6zLjhL7+ttA9TirBunvPmHCe3Oqs/iElskUJ3uBySmHxyEHgEQpX0YdduaFiYm8hmV7SSyMOQN9oHVwl2VRH5VjJKgbpR2ioQUncL6kspNlIzJcPyQOkT1LoaClknIIU2H/ifcJl2v64O23Qw/3dwnwxyrOOq3euA1KO8sMMnoLbhq1oKOM65OQK8oesLP0OTTe1I81T/w3NYT7TW+BiFFwqdCvKQXYEKrKb/9Vzp3jwzRH0Y4fYc4PluIJsPn7687Q/XSEniqQAqbw1WCGpYzIkQxN/WdF2fYDf4AGCCmu/rUEgH4TABcbBt0=~-1~-1~-1; ak_bmsc=BE34077C485C60FA083156B660C33446~000000000000000000000000000000~YAAQnAHorG4WRiSBAQAA6vnMaBBiR9Rlx1KlU/blctiI7Kh862F5JZqxRa3ut6wlIhjWYbglM16+cQy9wXTked1t9PWL6R9HoZ8W6yqpbkjYjoQjSnKSJIgBitTHRVMhZFlXrxQiekO2zjRSAbg8V+3ITJQHLWkxsqatK/khebyCrpI4adVsR8hdSLMZLsw8cA8HrYkepb8uh0PpsCZL5PgKLf0QNd1cPQCIy+ScbtLO9J7Zi8A6Tb4UNHVv+FZg9x35cMgz2O4GfLdHnbHMtR0IQha9ipR3RYwdUFFrR64JKUj9FUwJPLL23r9Dz4UNW20DILqog3hYHdF7jRd3t0SN20sbG/4RGLoiF7D0Yy2b9YXEcLj4Ga2jjATPby4+sDEyj/cWN+0zmFPbUlb44A==; bm_sz=AD1E5CF28066F552CAD338F16345D50D~YAAQnAHorG8WRiSBAQAA6vnMaBCtZs+mak0NrqIKIYRWnPpw1uMm66tFculBrnYkFuj6u9f+OC7Rs7tBWs6o17teBEV3/XyIVckspYvC1y68v3A88sZQq1iWxIDj4Xo/Yhd64epUWLFd80w9CYxd5BoQo0TftFWZ/e6dK8T4RthLPiLAc3oaruxXg/L0J/td07tnPLEgb2dDEeX4aP9RZdPj9ogdVVXa7eyMUaMc9o8ekRtLVlzNHFmp5pbELZ/47QNe8qSGJbsxesE1Jfu9Y/nCqVwY7WLnPbdTnAQ++1tJWGpWJrQl~3356211~3294533';
			if($ucookiemanual==0){ $headers[] = $cookie; }
	   
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
			curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 2);
			
			$result2 = curl_exec($ch);
			if (curl_errno($ch)) {
				echo 'Error:' . curl_error($ch);
				$updateSQL = sprintf("/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 3 */ UPDATE cookies SET errorcookie=errorcookie+1
				WHERE 	id_cookie = 1 AND cookinombre=%s",
				GetSQLValueString("twinspire", "text"));
				$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
				$query_Recordset112 = sprintf("/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 4 */ SELECT * 
					FROM 
					cookies 
					WHERE
					id_cookie = 1 AND cookinombre = %s
					LIMIT 1",
					GetSQLValueString("twinspire", "text"));   
				$Recordset112 = mysqli_query($conexionbanca, $query_Recordset112) or die(mysqli_error($conexionbanca));
				$row_Recordset112 = mysqli_fetch_assoc($Recordset112);
				$totalRows_Recordset112 = mysqli_num_rows($Recordset112);
				if($row_Recordset112['errorcookie']>5){
					$updateSQL = sprintf("/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 5 */ UPDATE cookies SET errorcookie=errorcookie+1, cookiefull=0
					WHERE 	id_cookie = 1 AND cookinombre=%s",
					GetSQLValueString("twinspire", "text"));
					$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));
				}
			}
			curl_close($ch);
	
	
	
	
	
	
	//$str_datos = get_url_contents($url); 
$fulldatos = json_decode($result2,true); 
//var_dump($fulldatos); 
//print_r($fulldatos); 
if (isset($fulldatos)) {
$x=0;

foreach($fulldatos as $CurrentRace) {
	print_r($CurrentRace); 
	echo 'aqui estoy<br><br><br><br><br><br>';
	$currentRaceNumber=$CurrentRace["currentRaceNumber"];

	$currentRaceNumbermenos1=$currentRaceNumber-1;
   $hipodomo[$x]=strtoupper($CurrentRace["brisCode"]);
   //echo '<br>';
   //echo $CurrentRace["brisCode"];
   //echo '<br><br>';
   $RaceStatus=$CurrentRace["races"][$currentRaceNumbermenos1]["status"];
 
   if ($RaceStatus=="Open"){

   if ($RaceStatus=="Off" OR $RaceStatus=="Closed") $restante[$x]=0;
       else if ($RaceStatus=="Open" && $CurrentRace["races"][$currentRaceNumbermenos1]["mtp"]==0) $restante[$x]=2;
           else $restante[$x]=$CurrentRace["races"][$currentRaceNumbermenos1]["mtp"];
   $numeroca[$x]=$CurrentRace["races"][$currentRaceNumbermenos1]["raceNumber"];
   $horaInicial=horaactual8();
   $minutoAnadir=$restante[$x];
   $segundos_horaInicial=strtotime($horaInicial);
   $segundos_minutoAnadir=$minutoAnadir*60;
   $nuevaHora=date("H:i",$segundos_horaInicial+$segundos_minutoAnadir);
   $horacier[$x]=$nuevaHora;
   $horacarr[$x]=$nuevaHora;
   echo ' hipodomo= '.$hipodomo[$x];
   echo ' numeroca= '.$numeroca[$x];
   echo ' RaceStatu= '.$RaceStatus.'<br>';
   $x++;
}}
}
return array($horacarr, $hipodomo, $numeroca, $restante, $horacier);	
}








list($horacarr, $hipodomo, $numeroca, $restante, $horacier)=consultaCierreTwinspires2($row_Recordset111['cookiefull'],$conexionbanca);
//var_dump($hipodomo);
$fech=fechaactualbd();
$horasistema=horaactual();
$query_Recordset1 = sprintf("/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 6 */ SELECT 
		hi.pre_twin,
		hi.nom_hipodromo,
		ca.cod_carrera,
		ca.num_carrera,
 		ca.est_carrera,
 		ca.hor_carrera,
		ca.est_cierre,
		ca.ABIERTOX,
		ca.horaapertura
	FROM carrera ca, hipodromo hi
	WHERE	ca.cod_hipodromo=hi.cod_hipodromo AND
ca.simulcast=0 AND
		ca.eje_primero=0 AND
		(ca.est_cierre=0  OR ca.est_cierre=1  OR ca.est_cierre=3) AND
        hi.mtp_twinspire=1 AND 
		(ca.est_carrera=0  OR ca.est_carrera=1) AND
		ca.eje_primero=0 AND 
		ca.fec_carrera=%s",





GetSQLValueString($fech, "date"));  
$Recordset1 = mysqli_query($conexionbanca, $query_Recordset1) or die(mysqli_error($conexionbanca));
$row_Recordset1 = mysqli_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysqli_num_rows($Recordset1);
echo 'totalRows_Recordset1= '.$totalRows_Recordset1;
?>
<?php
if ($totalRows_Recordset1>0) {
	$g=1;
    do {

		$f=0;
		$control=1;
		if ($hipodomo[0]!="") {
			foreach($hipodomo as $hip){
				if (($row_Recordset1['est_cierre']==0 OR $row_Recordset1['est_cierre']==1 OR $row_Recordset1['est_cierre']==3) && trim($hipodomo[$f])==trim($row_Recordset1['pre_twin']) && $numeroca[$f]==$row_Recordset1['num_carrera'] && $restante[$f]<=50) {
					$hor_carrera=$horacier[$f];
					$cod_carrera=$row_Recordset1['cod_carrera'];
					$cie=2;
	 
						$est=1;
					if ($est!=0) { 
						if($row_Recordset1['ABIERTOX']==0){$abiertox="TWINSPA";}else{$abiertox=0;}
						if($row_Recordset1['horaapertura']=='00:00:00'){$horaapertura=$horasistema;}else{$horaapertura=$row_Recordset1['horaapertura'];}
						if($row_Recordset1['est_cierre']==1){
							$carrA=$row_Recordset1['nom_hipodromo'].': ...'.$row_Recordset1['num_carrera'];
							$msj="Twinspire reabrio esta carrera" . "\n".$carrA;
							$msjx=utf8_encode($msj);
							$post=[
								'chat_id'=>-214345883,
								'text'=>$msjx,
							];
							$ch = curl_init();
							curl_setopt($ch, CURLOPT_URL,"https://api.telegram.org/bot309341364:AAETe6H8z5HXbqdv5XhpTEY-nsfBKtYQ0mE/sendMessage");
							curl_setopt($ch, CURLOPT_POST, 1);
							curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
							curl_exec ($ch);
							curl_close ($ch);
							
							
						}
							$updateSQL = sprintf("/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 7 */ UPDATE carrera SET 
							hor_carrera=%s, 
							hor_mtp=%s, 
							est_carrera=%s, 
							est_cierre=%s, 
							supercontrol=%s, 
                            ABIERTOX=%s, 
                            horaapertura=%s 
												  WHERE cod_carrera=%s",
													GetSQLValueString($hor_carrera, "date"),
													GetSQLValueString($hor_carrera, "date"),
													GetSQLValueString($est, "int"),
													GetSQLValueString($cie, "int"),
												    GetSQLValueString(0, "int"),
                                                    GetSQLValueString($abiertox, "text"),
													GetSQLValueString($horaapertura, "date"),
													GetSQLValueString($cod_carrera, "int"));
							$Result1 = mysqli_query($conexionbanca, $updateSQL) or die(mysqli_error($conexionbanca));


               
                $insertSQL2 = sprintf(
                    "/* PARSEADORES1 includes\twinspires_soloapertura_v4.php - QUERY 8 */ INSERT INTO quiencierrayabre 
					(codcarrera, 
					fechaquien, 
					que) 
					VALUES (%s, %s, %s)",
                    GetSQLValueString($cod_carrera, "int"),
                    GetSQLValueString($fechaactual, "date"),
                    GetSQLValueString(11, "int"));
                $Result12 = mysqli_query($conexionbanca, $insertSQL2) or die(mysqli_error($conexionbanca));








					}
					$g++;
					break;
				}
				$f++;
			}
		}
		
	} while ($row_Recordset1 = mysqli_fetch_assoc($Recordset1));
mysqli_free_result($Recordset1);
}}
?>