<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$cookie_file = "C:\laragon\www\twinspirecookie.text"; //direccion en windows
$proxyIP = '54.163.116.201';
$proxyPort = '808';
$proxyUsername = 'linode';
$proxyPassword = 'marca147';
$ch = curl_init();
//curl_setopt($ch, CURLOPT_URL, 'https://www.cual-es-mi-ip.net/');
curl_setopt($ch, CURLOPT_URL, 'https://www.twinspires.com/adw/todays-tracks?affid=2800&sortOrder=nextUp');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10); 
curl_setopt($ch, CURLOPT_TIMEOUT, 30); //timeout in seconds
curl_setopt ($ch, CURLOPT_COOKIEJAR, '../includes/twinspirecookie.txt'); //crear un cookie y lo guarda
//curl_setopt ($ch, CURLOPT_COOKIEFILE, $ckfile); //toma un cookie ya creado
//curl_setopt($ch, CURLOPT_HTTPPROXYTUNNEL, 1);
//curl_setopt($ch, CURLOPT_PROXY, '54.163.216.40:808'); 
//curl_setopt($ch, CURLOPT_PROXYUSERPWD, 'proxy.packetstream.io:3GLLRzF0I0y5SGzi_country-UnitedStates');
curl_setopt($ch, CURLOPT_HTTPPROXYTUNNEL , 1);
curl_setopt($ch, CURLOPT_PROXY, $proxyIP); //Set the proxy IP.
curl_setopt($ch, CURLOPT_PROXYPORT, $proxyPort); //Set the port.
//curl_setopt($ch, CURLOPT_PROXYUSERPWD, "$proxyUsername:$proxyPassword"); //Specify the username and password.


$headers = array();
$headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
$headers[] = 'Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3';
$headers[] = 'Connection: keep-alive';
//$headers[] = 'Cookie: _abck=B40FC1BDF04AFE972997FC03298A710E~-1~YAAQxpEvF/nMR6B8AQAAbEY7rQZRU8D7xh1Qtvci5a7QZr8ZDVaolGz6pCPJqip8F5PtGUzMpcg/eEJwaZ2LGvJcmAEefR1A5kv+NnIP7w39BDdrMFtz0MeeH1POka/GDYIo5AlU+YFoSUq0ZbOk/AaMf83DpJx5YEjdBy9Gk+VW2KNXF34fZ53upbHEcdYZyWUB4EN3t2Woi0VBdXTMxSP2elD+tVzTRFDc0CxCEcp3/O7CQPjIshGesWZXVGuuBKYAhMsIaR92xkr5ug6lggHYNmri6DPc7N4ernco0L/BjU9CtbxDF6H+FHdgYapsLFun8AU9IY2LLtyqhHD6iO45Cn7fmaEWTLx8h5/SNZIZ5y5PxioZpmkCtTIFSOHw~-1~-1~-1; ak_bmsc=859E0E687085614E269137946AEA1D1F~000000000000000000000000000000~YAAQxpEvF/rMR6B8AQAAbEY7rQ05G+0FvA/2XAgEi2fVzc7g6An7snsmwnwx26p7oIRw3CLX8KL5i+QQyHdEAdn8D6ubDkiKtjO25kPVvGh2xep11SCOdSnu8Cu+i2loxfRYW9c95uaUQ3kDci4ytevTqUv06rr1gfVT9QOBNM1hIE9ZH0DtKiZidx1itBkamG+0dNUB0tUzgAE4foaHJlEMQE1SR810i4/HM4yhKImsfT0Yt27VoqDxysCaPDCp/l/pJucKyXfTjGVad7hpoOwikGv/nYp5veDC1CutF86DWiW19M5kjgO96d75MP2VhYHKyuY7Af9CTYLQSI+HyyU/sdCeALNcOmNfMVeqrLuMOczkxGzlyC2N+SkGl8khJDeRmvLltiL31J+uP2qj; bm_sz=F598B30A345BCBC95315C301AEF6480D~YAAQxpEvF/vMR6B8AQAAbEY7rQ0Jj4zdgkaUQBUDZvh9NQHmMw4kY8pYho4W1YFlu4dqTzKXyEo4q/AL6KHPUjApFvgtrIEwnimp8X5WuDChIdmGTz5+iYY6kJpLh3cOCMD8mXnQc41HZrcz5U09bJ+Ckjo3L427qQ9bqhWDiuClR5LU+4bWKaVAsddlLvhTZ442XZL3k6pJYBIkL8s8ANXz1Pw82YF+WJlixCm/aAgm3asvo0cIWXEK9Mv6OdOsHO0r6u1nGRTLi3mu2s7L+UptWa3fn8s5dH5PG8pwNLGWjoi+CR6Y~4342084~4536118; bm_sv=3A88D4B8B67ADB8C03B0189976229726~QttlZ2Pvn7e0eeEr7LyzrQuDYPZgug1Ne+53ipe0zBsv0bNewmAagtX4sZyRIieMqCWIRgUCyhKiBv10qDsmRLbEwTotFyOtZ9Dp6cLZZ2lP4RIdt0PPDwR+FyRweM6+bKj6JzCPcuFjOA4oYJQPskmzyN8zSjxs/Z68CGvgEvI=';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Te: Trailers';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}else{
echo 'Se ejecuto';
}
curl_close($ch);


//var_dump($result); 