<?php



// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.capitalotbbet.com/adw/todays-tracks?affid=4200&sortOrder=nextUp');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 30);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: www.capitalotbbet.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: ^^Chromium^^\";v=^^\"94^^\",';
$headers[] = 'Sec-Ch-Ua-Mobile: ?1';
$headers[] = 'Sec-Ch-Ua-Platform: ^^Android^^\"\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Mobile Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: none';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Accept-Language: es-ES,es;q=0.9';
$headers[] = 'Cookie: _ga=GA1.2.2035704166.1632961824; _abck=1E1901C9E33F7098B096A0370919E087~0~YAAQ3JEvF4n0+pl8AQAALRSnnQa1Vrjqx2f7dEhjp7YYdvBgsUUgJfiFfZON+7bpZ0jS4ByJTUIMeJLRg9lCIcn9toAMqehUqSir0peDHUqGisBcnZlKlDaYbACU52wCG+iCU84gvNca073hQKBp7+GNLIMLvxYgeWwPoKWzB3QXPp3w1thoQAyIYIzESEucRVS/YUnx5VjPKVLaSYJW4PVZlHgVVFfkpQ2NkWffIbVRuACGX/pu6dnGyC0dsGBf1W91mX9XPJS7XO1+/faPEZHgUG45MzX3UgWyzYZFakBLNt6SrhFbkErBCFI9H9PaMIueQAfj2sd982SUqXeBKRk2ZdIbi+ZuzzACKUFf33CHFN0elVURPpDJGeqdl4UEEGwxpz0rMgEKBkaeH0BKIGx6BR+7v9MLbpMKnsw3bg==~-1~-1~-1; ak_bmsc=AEAEAB0D2C1786CE6B3B58D9F7DFA496~000000000000000000000000000000~YAAQ3JEvF4r0+pl8AQAALRSnnQ1Lb18ZmWkY0tzhq/zmLMOFGsKUo58lsL+d5ENQqht93u2y7UQP6TQkFL5jxW3mOEFNz5gRHIQpJ5SBk0W1F53IoTKZJ79aXY+y3hd7yJANu1xqfBNfqy7RJf5+Sj/GUi8heB8myIDyx6DxSOZ/q7dfD+XE9L+sgwas2t4+WbITUtmSdyvZI34BfAJm/68bhH/cs8Cr82nUpinpFCmggcvgOToeScHLn8yPADNZ9mZRKcnOkjGr1Noy6AlK6FSzq8kHHFl990jRgmfyB3yP+FxG2oTwN20VVO7IhJLBwBclZ6NTlJ/ex4gUBPn8UfNZuW50nZG/HoQXs0CnCjXJV17lsSSJkUoouxZ5k6C4k0UTydUQ7HUv0rN2r0X7Z0av; bm_sz=F01BF2D82B22ECA2EF8324B8B0CF599B~YAAQ3JEvF4v0+pl8AQAALRSnnQ39v3WWBhIxWdLRemNF6SOWwQ/Loxpww5lazgfPwLvsbfobPwhjttk8Xx4JjSmAIaLMyIzaTp4EpPwF4otXODl/iEwkbvlHbpVC82VlxmShmiKU+WzwtRVm6Luc6g25o7P/nJoiSW3NrV8YayTJywT9bU2L1/C0NKsBol7caj/wDWesnDxdmHiYanUARW+Vu8ZbUnwXi3amKEMwWywBKvtYvhw4TR1gS9aTyKf7OgnqtCfcOkd/TH5XSMnd7yzBob4MmvtzWvq/iJqst/DfcfDvXLoXpLSN~4407605~3621170';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
//$result= json_decode($result ,true); 
echo $result; 
//var_dump($result); 